//! `dropset-sdk` — off-chain Rust client for the Dropset eCLOB program.
//!
//! Two spines (interface.md § SDK):
//!
//! - **Generated client** ([`generated`]): the Codama output — instruction
//!   builders, account codecs, PDA helpers, program constants. Regenerate
//!   with `make sdk` after `make idl`.
//! - **Book math** ([`price`], [`layout`], [`matching`]): the `Price`
//!   codec and just-in-time book reconstruction the IDL can't describe
//!   (the `Vault` slab is opaque to it). Solana-free, so the same math can
//!   target `wasm32` for the TS consumer later.
//!
//! Router quoting adapters (e.g. DFlow) build on [`matching::simulate_swap`]
//! for quotes and the generated [`generated::instructions`] builders for
//! swap instructions.

// Autogenerated by Codama — not hand-maintained, so quiet the lints it
// trips (e.g. a flattening re-export the gated builders consume via
// `crate::`-qualified paths).
pub mod adapters;
#[allow(unused_imports)]
pub mod generated;
pub mod quoting;

// The solana-free arithmetic spine lives in `dropset-price-core` and is
// re-exported here so `crate::{price,layout,matching}` (used throughout the
// adapters and quoting) resolve, and downstream users get one import path.
pub use dropset_price_core::{layout, matching, price};

// The Codama renderer references some siblings as `crate::shared` /
// `crate::types` (crate-root) and others as `crate::generated::types`.
// Re-export the generated submodules at the crate root so both path
// forms resolve, and so downstream users get the ergonomic
// `dropset_sdk::instructions::*` surface.
pub use generated::{accounts, errors, instructions, programs, shared, types};
// The generated instruction builders reference the program id as
// `crate::DROPSET_ID`, so flatten the program constants to the crate root.
pub use generated::programs::DROPSET_ID;
