//! Generate the cross-language Price conformance vectors.
//!
//! `cargo run -p dropset-math-core --example gen_conformance` prints the
//! canonical JSON to stdout (or, with `--write`, writes it back to the
//! checked-in path — see `make conformance-vectors`); it is checked in at
//! `sdk/conformance/price_vectors.json` and verified in both Rust
//! (`tests/conformance.rs`) and TS (`sdk/ts/src/conformance.test.ts`).
//!
//! Scope (interface.md § SDK): the `Price` math. `simulate_swap`
//! conformance (which needs serialized market fixtures) is a follow-up.

use dropset_math_core::price::Price;
use serde_json::{json, Value};

fn decode_case(p: Price) -> Value {
    json!({ "bits": p.as_u32(), "value": p.to_f64(), "valid": p.is_valid() })
}

fn main() {
    // Regular prices spanning exponents + both sentinels.
    let prices = [
        Price::encode(10_000_000, 0).unwrap(),  // 1.0
        Price::encode(10_850_000, 0).unwrap(),  // 1.085 (EUR/USD)
        Price::encode(99_000_000, -1).unwrap(), // 0.99
        Price::encode(98_700_000, 2).unwrap(),  // 987.0
        Price::encode(10_000_000, -2).unwrap(), // 0.01
        Price::ZERO,
        Price::INFINITY,
    ];
    let decode: Vec<Value> = prices.iter().map(|p| decode_case(*p)).collect();

    // value -> bits (None serializes as null).
    let encode_values = [0.0_f64, 1.0, 1.085, 0.99, 987.0, 0.01];
    let encode: Vec<Value> = encode_values
        .iter()
        .map(|&v| json!({ "value": v, "bits": Price::from_value(v).map(|p| p.as_u32()) }))
        .collect();

    // Reject-path: inputs both forks must reject — `Price::from_value`
    // returns `None`, TS `encodePrice` throws `RangeError`. The agreed
    // contract is non-finite and negative input; serde can't emit NaN/±inf
    // as JSON numbers, so they ride as string tags the replays map back
    // (`"nan"`, `"inf"`, `"-inf"`). `bits` is always null (the reject
    // marker). Note what is *deliberately absent*: huge finite values
    // (e.g. 1e300) are NOT a conformable reject — Rust's saturating
    // f64->u64 cast normalizes them to a valid `Price` while TS throws, a
    // real divergence tracked separately, so pinning it here would wrongly
    // assert agreement.
    let encode_reject = json!([
        { "value": -1.0, "bits": Value::Null },
        { "value": "nan", "bits": Value::Null },
        { "value": "inf", "bits": Value::Null },
        { "value": "-inf", "bits": Value::Null },
    ]);

    // Ratio math (saturated to u64 for the JS/wasm boundary).
    let qfb_cases = [
        (Price::encode(10_000_000, 0).unwrap(), 1_000_000u64),
        (Price::encode(10_850_000, 0).unwrap(), 1_000_000),
        (Price::encode(10_000_000, -2).unwrap(), 1_000_000),
        (Price::encode(98_700_000, 2).unwrap(), 1_000),
    ];
    let quote_for_base: Vec<Value> = qfb_cases
        .iter()
        .map(|&(p, base)| {
            json!({ "bits": p.as_u32(), "base": base,
                    "expected": p.quote_for_base(base).min(u64::MAX as u128) as u64 })
        })
        .collect();

    let bfq_cases = [
        (Price::encode(10_000_000, 0).unwrap(), 1_000_000u64),
        (Price::encode(10_850_000, 0).unwrap(), 1_085_000),
    ];
    let base_for_quote: Vec<Value> = bfq_cases
        .iter()
        .map(|&(p, quote)| {
            json!({ "bits": p.as_u32(), "quote": quote,
                    "expected": p.base_for_quote(quote).min(u64::MAX as u128) as u64 })
        })
        .collect();

    let doc = json!({
        "_comment": "Generated by `cargo run -p dropset-math-core --example gen_conformance`. Do not edit by hand. Verified in Rust (sdk/math-core/tests/conformance.rs) and TS (sdk/ts/src/conformance.test.ts). Integer fields are exact; the float `value` is display-only and compared with a small relative tolerance (cross-language pow differs by ULPs); `value: null` is the INFINITY sentinel. `encode_reject` inputs must reject on both forks (Rust None / TS RangeError); non-finite values ride as string tags (\"nan\"/\"inf\"/\"-inf\").",
        "decode": decode,
        "encode": encode,
        "encode_reject": encode_reject,
        "quote_for_base": quote_for_base,
        "base_for_quote": base_for_quote,
    });
    emit(&doc, "price_vectors.json");
}

/// Print the canonical pretty JSON to stdout, or — with `--write` — write
/// it to the checked-in `sdk/conformance/<file>` so `make
/// conformance-vectors` can regenerate the vectors without a shell
/// redirect. The trailing newline matches `println!` either way, so the
/// CI freshness gate sees identical bytes.
fn emit(doc: &Value, file: &str) {
    let json = serde_json::to_string_pretty(doc).unwrap();
    if std::env::args().any(|a| a == "--write") {
        let dir = concat!(env!("CARGO_MANIFEST_DIR"), "/../conformance/");
        std::fs::write(format!("{dir}{file}"), format!("{json}\n")).unwrap();
    } else {
        println!("{json}");
    }
}
