//! Generate the cross-language Price conformance vectors.
//!
//! `cargo run -p dropset-math-core --example gen_conformance` prints the
//! canonical JSON to stdout (or, with `--write`, writes it back to the
//! checked-in path — see `make conformance-vectors`); it is checked in at
//! `sdk/conformance/price_vectors.json` and verified in both Rust
//! (`tests/conformance.rs`) and TS (`sdk/ts/src/conformance.test.ts`).
//!
//! Scope (interface.md § SDK): the `Price` math. `simulate_swap`
//! conformance (which needs serialized market fixtures) is a follow-up.

use dropset_math_core::price::Price;
use serde_json::{json, Value};

fn decode_case(p: Price) -> Value {
    json!({ "bits": p.as_u32(), "value": p.to_f64(), "valid": p.is_valid() })
}

fn main() {
    // Regular prices spanning exponents + both sentinels.
    let prices = [
        Price::encode(10_000_000, 0).unwrap(),  // 1.0
        Price::encode(10_850_000, 0).unwrap(),  // 1.085 (EUR/USD)
        Price::encode(99_000_000, -1).unwrap(), // 0.99
        Price::encode(98_700_000, 2).unwrap(),  // 987.0
        Price::encode(10_000_000, -2).unwrap(), // 0.01
        Price::ZERO,
        Price::INFINITY,
    ];
    let decode: Vec<Value> = prices.iter().map(|p| decode_case(*p)).collect();

    // value -> bits (None serializes as null). `1e12` is far above the FX
    // band but still fits the `u64` scaling intermediate, so it pins the
    // accept side of the reject boundary (it must NOT be rejected).
    let encode_values = [0.0_f64, 1.0, 1.085, 0.99, 987.0, 0.01, 1e12];
    let encode: Vec<Value> = encode_values
        .iter()
        .map(|&v| json!({ "value": v, "bits": Price::from_value(v).map(|p| p.as_u32()) }))
        .collect();

    // Reject-path: inputs both forks must reject — `Price::from_value`
    // returns `None`, TS `encodePrice` throws `RangeError`. The contract is
    // non-finite and negative input, plus any finite value so large that
    // `value * 1e7` overflows `u64` (e.g. `1e300`, `1e13`): both forks now
    // reject these rather than Rust silently saturating the `f64`->`u64`
    // cast to a bogus finite `Price`. serde can't emit NaN/±inf as JSON
    // numbers, so they ride as string tags the replays map back (`"nan"`,
    // `"inf"`, `"-inf"`); finite huge values stay JSON numbers. `bits` is
    // always null (the reject marker).
    let encode_reject = json!([
        { "value": -1.0, "bits": Value::Null },
        { "value": "nan", "bits": Value::Null },
        { "value": "inf", "bits": Value::Null },
        { "value": "-inf", "bits": Value::Null },
        { "value": 1e13, "bits": Value::Null },
        { "value": 1e300, "bits": Value::Null },
    ]);

    // Ratio math (saturated to u64 for the JS/wasm boundary).
    //
    // The spread is the same price x amount cross-product
    // `roundtrip_never_overcharges_taker` pins in-crate, so the TS fork —
    // which has no property test of its own — inherits the same rounding
    // coverage. Both decoders truncate toward zero, and most of these
    // combinations divide inexactly, so a fork that ceil'd or rounded
    // half-up disagrees here instead of passing a suite of exact
    // divisions. The minimal discriminating pairs are `quote_for_base` at
    // 1.085 with base 3, which must give 3 rather than 4, and
    // `base_for_quote` at 1.085 with quote 1, which must give 0 rather
    // than 1.
    let ratio_prices = [
        Price::encode(10_000_000, 0).unwrap(),  // 1.0
        Price::encode(10_850_000, 0).unwrap(),  // 1.085 (EUR/USD)
        Price::encode(33_333_333, 0).unwrap(),  // ~3.333, never exact
        Price::encode(98_700_000, 2).unwrap(),  // 987
        Price::encode(10_000_000, -2).unwrap(), // 0.01
        Price::encode(99_999_999, 5).unwrap(),  // large
    ];
    // 1_000 and 1_085_000 carry over the amounts the four `quote_for_base`
    // and two `base_for_quote` cases this cross-product replaced, so the
    // change only adds coverage.
    let ratio_amounts = [
        1_u64,
        3,
        7,
        999,
        1_000,
        1_000_000,
        1_085_000,
        1_085_321,
        7_777_777_777,
    ];

    let quote_for_base: Vec<Value> = ratio_prices
        .iter()
        .flat_map(|&p| {
            ratio_amounts.iter().map(move |&base| {
                json!({ "bits": p.as_u32(), "base": base,
                        "expected": p.quote_for_base(base).min(u64::MAX as u128) as u64 })
            })
        })
        .collect();

    let base_for_quote: Vec<Value> = ratio_prices
        .iter()
        .flat_map(|&p| {
            ratio_amounts.iter().map(move |&quote| {
                json!({ "bits": p.as_u32(), "quote": quote,
                        "expected": p.base_for_quote(quote).min(u64::MAX as u128) as u64 })
            })
        })
        .collect();

    let doc = json!({
        "_comment": "Generated by `cargo run -p dropset-math-core --example gen_conformance`. Do not edit by hand. Verified in Rust (sdk/math-core/tests/conformance.rs) and TS (sdk/ts/src/conformance.test.ts). Integer fields are exact; the float `value` is display-only and compared with a small relative tolerance (cross-language pow differs by ULPs); `value: null` is the INFINITY sentinel. `encode_reject` inputs must reject on both forks (Rust None / TS RangeError); non-finite values ride as string tags (\"nan\"/\"inf\"/\"-inf\").",
        "decode": decode,
        "encode": encode,
        "encode_reject": encode_reject,
        "quote_for_base": quote_for_base,
        "base_for_quote": base_for_quote,
    });
    emit(&doc, "price_vectors.json");
}

/// Print the canonical pretty JSON to stdout, or — with `--write` — write
/// it to the checked-in `sdk/conformance/<file>` so `make
/// conformance-vectors` can regenerate the vectors without a shell
/// redirect. The trailing newline matches `println!` either way, so the
/// CI freshness gate sees identical bytes.
fn emit(doc: &Value, file: &str) {
    let json = serde_json::to_string_pretty(doc).unwrap();
    if std::env::args().any(|a| a == "--write") {
        let dir = concat!(env!("CARGO_MANIFEST_DIR"), "/../conformance/");
        std::fs::write(format!("{dir}{file}"), format!("{json}\n")).unwrap();
    } else {
        println!("{json}");
    }
}
