-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: maker.yml
-- Regenerate: make dashboard-sql

SELECT
feed,
coalesce(extract(epoch FROM now()) - last_ok_at, 9999999)
::double precision AS ok_age_secs
FROM feed_health
