-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: maker.yml
-- Regenerate: make dashboard-sql

SELECT
market,
count(*)::double precision AS breaches
FROM maker_telemetry
WHERE ts > extract(epoch FROM now()) - 300
AND (degraded OR action = 'Halt')
GROUP BY market
