-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: maker.yml
-- Regenerate: make dashboard-sql

SELECT
feed,
(CASE WHEN state = 'up' THEN 0 ELSE 1 END)::double precision
AS link_down
FROM push_health
