-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: maker.yml
-- Regenerate: make dashboard-sql

SELECT
market,
(count(*) FILTER (WHERE tick_error IS NOT NULL))::double precision
/ greatest(count(*), 1) AS failing_fraction
FROM maker_telemetry
WHERE ts > extract(epoch FROM now()) - 300
GROUP BY market
