-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: maker.yml
-- Regenerate: make dashboard-sql

SELECT
coalesce(extract(epoch FROM now()) - max(ts), 9999999)
::double precision AS age_secs
FROM maker_telemetry
