-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: maker.yml
-- Regenerate: make dashboard-sql

SELECT
h.feed,
coalesce(extract(epoch FROM now()) - h.last_ok_at, 9999999)
::double precision AS ok_age_secs
FROM feed_health AS h
WHERE NOT EXISTS (
SELECT 1 FROM parked_source_feeds AS p WHERE p.feed = h.feed
)
