// cspell:word segoe

import countries from "world-countries";
import { IS_LOCALNET } from "../env";
import data from "./currencies.json";
// Localnet mint overlay: symbol → { mint, tokenProgram } for the mock demo
// mints the TUI bootstrap creates (tui/src/market.rs, from the checked-in
// keys/*.json). Applied only on localnet, in place of the real mainnet mints.
import localnetMints from "./currencies.localnet.json";
// Generated by scripts/fetch-token-icons.mjs: symbol → "/token-icons/<file>".
// Symbols missing from the manifest (e.g. newly added token before the next
// build) fall back to the canonical remote URL in currencies.json.
import iconManifest from "./icon-manifest.gen.json";

const ICON_OVERRIDES = iconManifest as Record<string, string>;
for (const entry of Object.values(data)) {
  for (const s of entry.stablecoins) {
    const local = ICON_OVERRIDES[s.symbol];
    if (local) s.icon = local;
  }
}

// On a local validator the demo tokens are mock SPL mints, not the real
// mainnet mints, so swap in their addresses — and force the classic Token
// program, since the bootstrap mints every mock mint under SPL Token even
// where mainnet uses Token-2022 (e.g. ZARP). Decimals already match the real
// tokens, so only mint + tokenProgram change. Mutates `data` in place before
// the lookup tables below derive from it, exactly like the icon overrides.
if (IS_LOCALNET) {
  const overlay = localnetMints as Record<
    string,
    { mint: string; tokenProgram: TokenProgramKind }
  >;
  for (const entry of Object.values(data)) {
    for (const s of entry.stablecoins) {
      const o = overlay[s.symbol];
      if (o) {
        s.mint = o.mint;
        s.tokenProgram = o.tokenProgram;
      }
    }
  }
}

export type IsoCurrencyCode = keyof typeof data;
export type Issuer = {
  name: string[];
  url: string;
  socials?: { x?: string };
};
export type TokenProgramKind = "classic" | "token2022";
export type Stablecoin = {
  symbol: string;
  name: string;
  mint: string;
  mintSourceUrl?: string;
  decimals: number;
  tokenProgram: TokenProgramKind;
  icon: string;
  issuer: Issuer;
};
export type CurrencyEntry = {
  anchorCca2?: string;
  stablecoins: Stablecoin[];
};

export const CURRENCIES = data as Record<IsoCurrencyCode, CurrencyEntry>;

const NAME_BY_CODE: Record<string, string> = {};
for (const c of countries) {
  for (const [code, info] of Object.entries(c.currencies ?? {})) {
    if (!NAME_BY_CODE[code]) NAME_BY_CODE[code] = info.name;
  }
}

const ALL_CURRENCY_CODES = (() => {
  const set = new Set<string>();
  for (const c of countries) {
    for (const code of Object.keys(c.currencies ?? {})) set.add(code);
  }
  return set;
})();

export const currencyStats = (): {
  represented: number;
  total: number;
  missing: number;
} => {
  const represented = SUPPORTED.filter((c) => ALL_CURRENCY_CODES.has(c)).length;
  const total = ALL_CURRENCY_CODES.size;
  return { represented, total, missing: total - represented };
};

export const SUPPORTED: IsoCurrencyCode[] = Object.keys(
  CURRENCIES,
) as IsoCurrencyCode[];

const STABLE_BY_SYMBOL: Record<string, Stablecoin> = (() => {
  const map: Record<string, Stablecoin> = {};
  for (const code of SUPPORTED) {
    for (const s of CURRENCIES[code].stablecoins) {
      if (map[s.symbol]) {
        throw new Error(
          `Duplicate stablecoin symbol "${s.symbol}" in currencies.json — symbols must be globally unique to safely populate slug → pair lookup tables.`,
        );
      }
      map[s.symbol] = s;
    }
  }
  return map;
})();

export const ALL_STABLECOIN_MINTS: string[] = Object.values(
  STABLE_BY_SYMBOL,
).map((s) => s.mint);

const STABLE_BY_MINT: Record<string, Stablecoin> = Object.fromEntries(
  Object.values(STABLE_BY_SYMBOL).map((s) => [s.mint, s]),
);

export const stablecoinByMint = (mint: string): Stablecoin | undefined =>
  STABLE_BY_MINT[mint];

// Case-insensitive lookup that yields the canonical-cased symbol (e.g. the
// JSON's `tGBP` rather than `TGBP`). Used by URL slug resolution.
const SYMBOL_BY_UPPER: Record<string, string> = Object.fromEntries(
  SUPPORTED.flatMap((code) =>
    CURRENCIES[code].stablecoins.map((s) => [s.symbol.toUpperCase(), s.symbol]),
  ),
);

const CURRENCY_BY_SYMBOL: Record<string, IsoCurrencyCode> = Object.fromEntries(
  SUPPORTED.flatMap((code) =>
    CURRENCIES[code].stablecoins.map((s) => [s.symbol, code]),
  ),
);

export const defaultStablecoin = (code: IsoCurrencyCode): string => {
  const first = CURRENCIES[code].stablecoins[0];
  if (!first) {
    throw new Error(
      `Currency "${code}" has zero stablecoins in currencies.json — defaultStablecoin can't return one.`,
    );
  }
  return first.symbol;
};

export const currencyName = (code: IsoCurrencyCode): string =>
  NAME_BY_CODE[code] ?? code;

// Path to a Twemoji flag SVG mirrored into public/flag-icons by
// scripts/copy-flags.mjs (1:1 viewBox, rounded-square glyph). Twemoji has
// distinct artwork for territories whose ISO-official flag is just the
// parent country's tricolor (PM, YT, RE, GP, MF, BL, MF, WF…) — the
// emoji-style unofficial regional designs people recognize. We bundle
// Twemoji SVGs because Windows' default emoji font (Segoe UI Emoji)
// renders regional-indicator pairs as plain letter pairs ("US", "GB")
// rather than as flags.
export const flagUrl = (cca2: string): string =>
  `/flag-icons/${cca2.toLowerCase()}.svg`;

// ISO 4217 currency codes are conventionally country-code + currency initial,
// so the first two letters give a usable cca2 (USD→US, EUR→EU, GBP→GB…).
export const currencyFlagUrl = (code: IsoCurrencyCode): string =>
  flagUrl(code.slice(0, 2));

export const currencyAnchor = (code: IsoCurrencyCode): string =>
  CURRENCIES[code].anchorCca2 ?? code.slice(0, 2);

export const tokenIconUrl = (symbol: string): string =>
  STABLE_BY_SYMBOL[symbol]?.icon ?? "";

// Look up a stablecoin's decimals by symbol. Throws on unknown symbols
// because the previous silent fallback to 0 produced ~10^6× wrong-scale
// quotes when an invalid symbol slipped through (e.g. URL tampering, or
// a stale tab after a stablecoin was removed from currencies.json). In
// the normal path every symbol the store can hold has come through
// resolveTokenSlug / setToken, both of which only emit canonical entries.
export const stablecoinDecimals = (symbol: string): number => {
  const decimals = STABLE_BY_SYMBOL[symbol]?.decimals;
  if (decimals === undefined) {
    throw new Error(
      `Unknown stablecoin symbol "${symbol}" — not present in currencies.json.`,
    );
  }
  return decimals;
};

export const stablecoinMint = (symbol: string): string =>
  STABLE_BY_SYMBOL[symbol]?.mint ?? "";

export const stablecoinTokenProgram = (
  symbol: string,
): TokenProgramKind | undefined => STABLE_BY_SYMBOL[symbol]?.tokenProgram;

// Collapse a base58 mint to "abcd…abcd" for at-a-glance display; copy and
// explorer surfaces should keep the full address.
export const shortenMint = (mint: string): string =>
  mint.length <= 11 ? mint : `${mint.slice(0, 4)}…${mint.slice(-4)}`;

// Cap a long token name at ~18 chars so outliers don't blow up the picker
// row. The CSS `truncate` on the surrounding span still handles narrow
// containers; this hard cap exists to clamp the row at a consistent width
// across all view ports for any one unusually long name that would otherwise
// dominate the layout. Tune by inspecting name-length distribution in
// `currencies.json` — pick a value just above the long tail.
const MAX_TOKEN_NAME_LEN = 18;
export const truncateTokenName = (name: string): string =>
  name.length <= MAX_TOKEN_NAME_LEN
    ? name
    : `${name.slice(0, MAX_TOKEN_NAME_LEN - 1).trimEnd()}…`;

export const ALL_STABLECOINS: readonly Stablecoin[] =
  Object.values(STABLE_BY_SYMBOL);

export const currencyForStablecoin = (
  symbol: string,
): IsoCurrencyCode | undefined => CURRENCY_BY_SYMBOL[symbol];

// Resolve a URL slug to a (currency, stablecoin) pair. Accepts either a
// stablecoin symbol (case-insensitive, returned in canonical case) or an ISO
// currency code (expands to that currency's default stablecoin). Returns null
// for anything else.
export const resolveTokenSlug = (
  raw: string | null | undefined,
): { currency: IsoCurrencyCode; stablecoin: string } | null => {
  if (!raw) return null;
  const upper = raw.toUpperCase();
  const canonical = SYMBOL_BY_UPPER[upper];
  if (canonical) {
    // CURRENCY_BY_SYMBOL is built from the same source as SYMBOL_BY_UPPER,
    // so every canonical symbol has a currency entry by construction.
    const currency = CURRENCY_BY_SYMBOL[canonical];
    if (currency) return { currency, stablecoin: canonical };
  }
  if (upper in CURRENCIES) {
    const cc = upper as IsoCurrencyCode;
    return { currency: cc, stablecoin: defaultStablecoin(cc) };
  }
  return null;
};

export type TokenSide = { currency: IsoCurrencyCode; stablecoin: string };
export type SidePair = { from: TokenSide; to: TokenSide };

export const DEFAULT_FROM: TokenSide = {
  currency: "USD" as IsoCurrencyCode,
  stablecoin: "USDC",
};
export const DEFAULT_TO: TokenSide = {
  currency: "EUR" as IsoCurrencyCode,
  stablecoin: "EURC",
};

// Canonical slug → pair resolver used by both the store factory (initial
// seed from window.location) and UrlSync (reconciliation from URL). Single
// source of truth so the conflict-resolution rule cannot drift between sites.
//
// Rules:
//   - Both slugs missing → defaults.
//   - Both present and resolve to the same stablecoin → keep the user's
//     explicit `from`, replace `to` with a non-conflicting default.
//   - Only one slug → resolve it; pick a default for the other side that
//     doesn't collide.
//   - Unknown slugs are treated as missing.
export const resolvePair = (
  fromSlug: string | null | undefined,
  toSlug: string | null | undefined,
): SidePair => {
  const f = resolveTokenSlug(fromSlug);
  const t = resolveTokenSlug(toSlug);
  if (!f && !t) return { from: DEFAULT_FROM, to: DEFAULT_TO };
  const slugConflict = !!(f && t && f.stablecoin === t.stablecoin);
  let from: TokenSide = f ?? DEFAULT_FROM;
  let to: TokenSide = t && !slugConflict ? t : DEFAULT_TO;
  if (from.stablecoin === to.stablecoin) {
    const fallback = (avoid: string): TokenSide =>
      avoid === DEFAULT_TO.stablecoin ? DEFAULT_FROM : DEFAULT_TO;
    if (f) to = fallback(from.stablecoin);
    else if (t) from = fallback(to.stablecoin);
  }
  return { from, to };
};
