import type { WalletConnector } from "@solana/client";
// Generated by scripts/fetch-wallet-icons.mjs: key → "/wallet-icons/<file>".
// Overlays the canonical remote URLs in wallets.json with the local mirror so
// the browser hits our own origin; unmirrored icons fall back to the remote.
import iconManifest from "./wallet-manifest.gen.json";
import walletsData from "./wallets.json";

// Wallets we always surface in the picker, even when none are installed, so a
// user on a fresh browser / mobile / incognito still sees their options. Order
// is the display order within each (detected / not-detected) group. `key` is a
// lowercase token matched against live Wallet Standard connectors by name;
// `site` is the wallet's official download page (only used for wallets that
// can't be connected to right now — installed ones connect instead).
export type KnownWallet = {
  key: string;
  name: string;
  icon: string;
  site: string;
};

const ICON_OVERRIDES = iconManifest as Record<string, string>;

export const KNOWN_WALLETS: readonly KnownWallet[] = (
  walletsData as KnownWallet[]
).map((w) => ({ ...w, icon: ICON_OVERRIDES[w.key] ?? w.icon }));

export type PickerWallet = {
  // Stable React key: the connector id when one exists, else a synthetic id.
  id: string;
  // Lowercase token from the curated list (`KnownWallet["key"]`) when the row
  // originates from a curated entry; undefined for an "extra" wallet
  // discovered solely via Wallet Standard. The renderer uses this to apply
  // wallet-specific affordances (e.g. gate the MetaMask row on relay-SDK
  // registration readiness).
  key?: string;
  name: string;
  icon?: string;
  detected: boolean;
  // Present iff connectable right now → render a connect button. Curated
  // extension wallets only have a connector when installed; MetaMask's relay
  // connector is always registered, so MetaMask stays connectable even while
  // "not detected".
  connectorId?: string;
  // Present iff there's nothing to connect to → render a link to the wallet's
  // official site so the user can install it.
  site?: string;
};

export type PickerWallets = {
  detected: PickerWallet[];
  notDetected: PickerWallet[];
};

const matchesKey = (connector: WalletConnector, key: string): boolean =>
  connector.name.toLowerCase().includes(key) ||
  connector.id.toLowerCase().includes(key);

const isKnown = (connector: WalletConnector): boolean =>
  KNOWN_WALLETS.some((w) => matchesKey(connector, w.key));

/**
 * Merge the curated wallet list with the live discovered connectors into two
 * display groups. MetaMask's badge is gated on a real extension
 * (`metamaskInstalled`) rather than its relay registration, so it can show as
 * "Not detected" yet still be connectable.
 */
export function buildPickerWallets(
  connectors: readonly WalletConnector[],
  metamaskInstalled: boolean,
): PickerWallets {
  const curated: PickerWallet[] = KNOWN_WALLETS.map((w) => {
    const connector = connectors.find((c) => matchesKey(c, w.key));
    const detected =
      w.key === "metamask" ? metamaskInstalled : connector !== undefined;
    return {
      id: connector?.id ?? `known:${w.key}`,
      key: w.key,
      name: w.name,
      // Prefer the live connector's own icon; fall back to the bundled brand
      // icon so not-installed wallets still show a real logo.
      icon: connector?.icon ?? w.icon,
      detected,
      connectorId: connector?.id,
      // Only offer the install link when there's no connector to connect to.
      site: connector ? undefined : w.site,
    };
  });

  // Any other wallet the user genuinely has (e.g. Brave) — always detected,
  // since extension wallets only register once installed. Exclude anything
  // matching a curated entry so a duplicate (e.g. MetaMask extension + relay)
  // can't render twice.
  const extras: PickerWallet[] = connectors
    .filter((c) => !isKnown(c))
    .map((c) => ({
      id: c.id,
      name: c.name,
      icon: c.icon,
      detected: true,
      connectorId: c.id,
    }));

  const all = [...curated, ...extras];
  return {
    detected: all.filter((w) => w.detected),
    notDetected: all.filter((w) => !w.detected),
  };
}
