import type { WalletConnector } from "@solana/client";
// Generated by scripts/fetch-wallet-icons.mjs: key → "/wallet-icons/<file>".
// Consulted as a lookup rather than merged into the imported data, so the
// canonical remote URL in wallets.json always survives behind the mirror.
// Overwriting `w.icon` in place used to destroy it, which left a wallet whose
// mirrored file was missing or unreadable with no recovery path at all — the
// picker rendered an empty box, silently. See walletIconUrl below.
import iconManifest from "./wallet-manifest.gen.json";
import walletsData from "./wallets.json";

// Wallets we always surface in the picker, even when none are installed, so a
// user on a fresh browser / mobile / incognito still sees their options. Order
// is the display order within each (detected / not-detected) group. `key` is a
// lowercase token matched against live Wallet Standard connectors by name;
// `site` is the wallet's official download page (only used for wallets that
// can't be connected to right now — installed ones connect instead).
export type KnownWallet = {
  key: string;
  name: string;
  // The vendor's canonical URL, exactly as committed — never the mirrored
  // path. Read it through `walletIconUrl` to get the mirror-first resolution.
  icon: string;
  site: string;
};

const ICON_OVERRIDES = iconManifest as Record<string, string>;

export const KNOWN_WALLETS: readonly KnownWallet[] =
  walletsData as KnownWallet[];

const KNOWN_BY_KEY: Record<string, KnownWallet> = Object.fromEntries(
  KNOWN_WALLETS.map((w) => [w.key, w]),
);

// Preferred icon source: the build-time mirror on our own origin, falling
// back to the wallet's canonical URL when the key is absent from the manifest
// (a wallet added since the last build, or one whose fetch failed).
export const walletIconUrl = (key: string): string =>
  ICON_OVERRIDES[key] ?? KNOWN_BY_KEY[key]?.icon ?? "";

// The canonical vendor URL, kept reachable so a render-side error handler can
// retry off-origin when the mirrored file is missing or unreadable. Returns
// "" when it is already what walletIconUrl produced, so a caller can tell
// "nothing further to try" from "try this next" without comparing strings.
export const walletIconFallbackUrl = (key: string): string => {
  const canonical = KNOWN_BY_KEY[key]?.icon ?? "";
  return ICON_OVERRIDES[key] ? canonical : "";
};

export type PickerWallet = {
  // Stable React key: the connector id when one exists, else a synthetic id.
  id: string;
  // Lowercase token from the curated list (`KnownWallet["key"]`) when the row
  // originates from a curated entry; undefined for an "extra" wallet
  // discovered solely via Wallet Standard. The renderer uses this to apply
  // wallet-specific affordances (e.g. gate the MetaMask row on relay-SDK
  // registration readiness).
  key?: string;
  name: string;
  icon?: string;
  // The second icon source to try when `icon` fails to load, "" when there is
  // none. Non-empty only for a curated brand icon served from our mirror —
  // the one shape with a canonical vendor URL behind it. Optional because
  // callers outside `buildPickerWallets` needn't supply it; that function
  // always does.
  iconFallback?: string;
  detected: boolean;
  // Present iff connectable right now → render a connect button. Curated
  // extension wallets only have a connector when installed; MetaMask's relay
  // connector is always registered, so MetaMask stays connectable even while
  // "not detected".
  connectorId?: string;
  // Present iff there's nothing to connect to → render a link to the wallet's
  // official site so the user can install it.
  site?: string;
};

export type PickerWallets = {
  detected: PickerWallet[];
  notDetected: PickerWallet[];
};

const matchesKey = (connector: WalletConnector, key: string): boolean =>
  connector.name.toLowerCase().includes(key) ||
  connector.id.toLowerCase().includes(key);

const isKnown = (connector: WalletConnector): boolean =>
  KNOWN_WALLETS.some((w) => matchesKey(connector, w.key));

/**
 * Merge the curated wallet list with the live discovered connectors into two
 * display groups. MetaMask's badge is gated on a real extension
 * (`metamaskInstalled`) rather than its relay registration, so it can show as
 * "Not detected" yet still be connectable.
 */
export function buildPickerWallets(
  connectors: readonly WalletConnector[],
  metamaskInstalled: boolean,
): PickerWallets {
  const curated: PickerWallet[] = KNOWN_WALLETS.map((w) => {
    const connector = connectors.find((c) => matchesKey(c, w.key));
    const detected =
      w.key === "metamask" ? metamaskInstalled : connector !== undefined;
    // One binding feeds both the source and its fallback, so the two can't
    // disagree about what "the connector supplied an icon" means. `||` rather
    // than `??` on purpose: an empty-string icon is no icon, and treating it
    // as one would skip the mirror and render the vendor URL directly.
    const connectorIcon = connector?.icon || undefined;
    return {
      id: connector?.id ?? `known:${w.key}`,
      key: w.key,
      name: w.name,
      // Prefer the live connector's own icon; fall back to the bundled brand
      // icon so not-installed wallets still show a real logo.
      icon: connectorIcon ?? walletIconUrl(w.key),
      // Only the bundled icon has a second source worth trying. A connector's
      // icon is an inline data URI carrying its own bytes, so there is no
      // fetch that can fail and nothing to promote it to.
      iconFallback: connectorIcon ? "" : walletIconFallbackUrl(w.key),
      detected,
      connectorId: connector?.id,
      // Only offer the install link when there's no connector to connect to.
      site: connector ? undefined : w.site,
    };
  });

  // Any other wallet the user genuinely has (e.g. Brave) — always detected,
  // since extension wallets only register once installed. Exclude anything
  // matching a curated entry so a duplicate (e.g. MetaMask extension + relay)
  // can't render twice.
  const extras: PickerWallet[] = connectors
    .filter((c) => !isKnown(c))
    .map((c) => ({
      id: c.id,
      name: c.name,
      icon: c.icon,
      // No curated entry, so no canonical URL to promote to. Spelled "" like
      // every other "nothing further to try" in this module rather than left
      // absent, so the field is total across all three row shapes.
      iconFallback: "",
      detected: true,
      connectorId: c.id,
    }));

  const all = [...curated, ...extras];
  return {
    detected: all.filter((w) => w.detected),
    notDetected: all.filter((w) => !w.detected),
  };
}
