-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: fx-analytics.json
-- Regenerate: make dashboard-sql

WITH days AS (
  SELECT generate_series(
           LEAST(
             (now() AT TIME ZONE 'America/New_York')::date - interval '2 years',
             COALESCE(
               (SELECT to_timestamp(min(bucket_start)) AT TIME ZONE 'America/New_York'
                FROM cex_prices),
               (now() AT TIME ZONE 'America/New_York')::date
             )
           ),
           (now() AT TIME ZONE 'America/New_York')::date + interval '14 days',
           interval '1 day'
         ) AS d
)
SELECT
  (d + interval '17 hours') AT TIME ZONE 'America/New_York' AS "time",
  (d + interval '2 days 17 hours') AT TIME ZONE 'America/New_York' AS "timeEnd",
  'FX market closed' AS text
FROM days
WHERE EXTRACT(DOW FROM d) = 5
ORDER BY 1
