-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: fx-analytics.json
-- Regenerate: make dashboard-sql

WITH bars AS (
  SELECT bucket_start, close
  FROM cex_prices
  WHERE $__unixEpochFilter(bucket_start)
    AND source = '$venue_source'
    AND product_id = '$venue_product'
    AND granularity_secs::text = '$granularity'
),
returns AS (
  SELECT
    to_timestamp(bucket_start) AS bucket_ts,
    CASE
      WHEN lag(bucket_start) OVER w = bucket_start - NULLIF('$granularity', '')::bigint
           AND lag(close) OVER w > 0
           AND close > 0
      THEN ln(close / lag(close) OVER w)
    END AS r
  FROM bars
  WINDOW w AS (ORDER BY bucket_start)
),
classified AS (
  SELECT
    EXTRACT(HOUR FROM bucket_ts AT TIME ZONE '$hour_tz')::int AS hour_of_day,
    CASE
      WHEN EXTRACT(DOW FROM bucket_ts AT TIME ZONE 'America/New_York') = 6
        THEN 'weekend'
      WHEN EXTRACT(DOW FROM bucket_ts AT TIME ZONE 'America/New_York') = 0
           AND EXTRACT(HOUR FROM bucket_ts AT TIME ZONE 'America/New_York') < 17
        THEN 'weekend'
      WHEN EXTRACT(DOW FROM bucket_ts AT TIME ZONE 'America/New_York') = 5
           AND EXTRACT(HOUR FROM bucket_ts AT TIME ZONE 'America/New_York') >= 17
        THEN 'weekend'
      ELSE 'weekday'
    END AS regime,
    r
  FROM returns
)
SELECT
  lpad(hour_of_day::text, 2, '0') AS hour,
  stddev_samp(r) FILTER (WHERE regime = 'weekday') * 10000 AS weekday,
  stddev_samp(r) FILTER (WHERE regime = 'weekend') * 10000 AS weekend
FROM classified
GROUP BY hour_of_day
ORDER BY hour_of_day
