-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: fx-analytics.json
-- Regenerate: make dashboard-sql

WITH bars AS (
  SELECT bucket_start, close
  FROM cex_prices
  WHERE $__unixEpochFilter(bucket_start)
    AND source = '$venue_source'
    AND product_id = '$venue_product'
    AND granularity_secs::text = '$granularity'
),
returns AS (
  SELECT
    to_timestamp(bucket_start) AS bucket_ts,
    CASE
      WHEN lag(bucket_start) OVER w = bucket_start - NULLIF('$granularity', '')::bigint
           AND lag(close) OVER w > 0
           AND close > 0
      THEN ln(close / lag(close) OVER w)
    END AS r
  FROM bars
  WINDOW w AS (ORDER BY bucket_start)
),
sessions (session, tz, open_hour, close_hour) AS (
  VALUES
    ('1 Sydney',   'Australia/Sydney', 8, 17),
    ('2 Tokyo',    'Asia/Tokyo',       9, 18),
    ('3 London',   'Europe/London',    8, 17),
    ('4 New York', 'America/New_York', 8, 17)
)
SELECT
  s.session,
  stddev_samp(r.r) * 10000 AS vol_bps_per_bar
FROM returns r
JOIN sessions s
  ON EXTRACT(HOUR FROM r.bucket_ts AT TIME ZONE s.tz) >= s.open_hour
 AND EXTRACT(HOUR FROM r.bucket_ts AT TIME ZONE s.tz) < s.close_hour
 AND EXTRACT(DOW FROM r.bucket_ts AT TIME ZONE s.tz) BETWEEN 1 AND 5
GROUP BY s.session
ORDER BY s.session
