-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: fx-analytics.json
-- Regenerate: make dashboard-sql

-- The tick tier, one line per venue for one product. Every other panel on
-- this dashboard reads cex_prices, so a venue that only writes spot_ticks
-- (kraken, erapi, frankfurter, pyth) is invisible to them; this is where
-- those venues are represented on the page. coinbase writes both tiers.
--
-- AVERAGED PER DISPLAY INTERVAL because the default window is thirty days and
-- a minute-cadence venue prints tens of thousands of ticks across it. The
-- column is bare inside both macros: Grafana captures a macro argument with a
-- regex that stops at the first closing paren, so a to_timestamp(...) inside
-- one truncates the argument. The group alias emits epoch seconds, which the
-- time_series format reads as time directly.
SELECT
  $__unixEpochGroupAlias(observed_at, $__interval),
  source AS metric,
  avg(price) AS value
FROM spot_ticks
WHERE $__unixEpochFilter(observed_at)
  AND source = ANY (ARRAY[${tick_source:sqlstring}]::text[])
  AND product_id = ${tick_product:sqlstring}
GROUP BY 1, 2
ORDER BY 1, 2
