-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: fx-analytics.json
-- Regenerate: make dashboard-sql

SELECT
  to_timestamp(bucket_start) AS "time",
  "open",
  "high",
  "low",
  "close",
  "volume"
FROM cex_prices
WHERE $__unixEpochFilter(bucket_start)
  AND source = ${venue_source:sqlstring}
  AND product_id = ${venue_product:sqlstring}
  AND granularity_secs::text = ${granularity:sqlstring}
ORDER BY bucket_start
