-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: fx-analytics.json
-- Regenerate: make dashboard-sql

WITH bars AS (
  SELECT bucket_start, close, high, low
  FROM cex_prices
  WHERE $__unixEpochFilter(bucket_start)
    AND source = '$venue_source'
    AND product_id = '$venue_product'
    AND granularity_secs::text = '$granularity'
),
regimes AS (
  SELECT
    bucket_start,
    close,
    high,
    low,
    CASE
      WHEN EXTRACT(DOW FROM to_timestamp(bucket_start) AT TIME ZONE 'America/New_York') = 6
        THEN 'weekend'
      WHEN EXTRACT(DOW FROM to_timestamp(bucket_start) AT TIME ZONE 'America/New_York') = 0
           AND EXTRACT(HOUR FROM to_timestamp(bucket_start) AT TIME ZONE 'America/New_York') < 17
        THEN 'weekend'
      WHEN EXTRACT(DOW FROM to_timestamp(bucket_start) AT TIME ZONE 'America/New_York') = 5
           AND EXTRACT(HOUR FROM to_timestamp(bucket_start) AT TIME ZONE 'America/New_York') >= 17
        THEN 'weekend'
      ELSE 'weekday'
    END AS regime
  FROM bars
),
returns AS (
  SELECT
    regime,
    close,
    high,
    low,
    CASE
      WHEN lag(bucket_start) OVER w = bucket_start - NULLIF('$granularity', '')::bigint
           AND lag(close) OVER w > 0
           AND close > 0
      THEN ln(close / lag(close) OVER w)
    END AS r
  FROM regimes
  WINDOW w AS (ORDER BY bucket_start)
)
SELECT
  regime,
  count(*) AS bars,
  count(r) AS return_pairs,
  stddev_samp(r) * 10000 AS vol_bps_per_bar,
  avg(abs(r)) * 10000 AS mean_abs_move_bps,
  max(abs(r)) * 10000 AS max_abs_move_bps,
  count(DISTINCT close) AS distinct_closes,
  count(*) FILTER (WHERE high = low) AS zero_range_bars
FROM returns
GROUP BY regime
ORDER BY regime
