-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: fx-analytics.json
-- Regenerate: make dashboard-sql

SELECT
  source,
  product_id,
  count(*) AS bars,
  to_timestamp(max(bucket_start)) AS last_bar,
  (extract(epoch FROM now()) - max(bucket_start))::bigint AS age
FROM cex_prices
GROUP BY source, product_id
ORDER BY source, product_id
