-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: fx-analytics.json
-- Regenerate: make dashboard-sql

-- Cross-pair overlay, indexed to 100 at each series' first bar INSIDE the
-- window. Absolute levels are not comparable across pairs -- EUR-USD sits
-- near 1.08 while EUR-JPY sits near 170 -- so an overlay of raw closes is one
-- flat line and one off-scale line, and "which moved most" has no readable
-- answer. Indexing puts every pair on a common percent axis.
--
-- The base is the first bar in the WINDOW, not the series' first bar ever, so
-- panning or zooming re-bases every series and the comparison stays about the
-- period actually on screen.
--
-- Scoped to the selected venue, matching how the rest of this dashboard
-- reads: one venue at a time. Two vendors carrying the same pair would
-- otherwise draw two nearly-identical lines and double the legend for no
-- information.
WITH bars AS (
  SELECT
    product_id,
    bucket_start,
    close
  FROM cex_prices
  WHERE $__unixEpochFilter(bucket_start)
    AND source = ${venue_source:sqlstring}
    AND product_id = ANY (ARRAY[${pairs:sqlstring}]::text[])
    AND granularity_secs::text = ${granularity:sqlstring}
),

base AS (
  -- The earliest bar each pair has in the window, which is its index base.
  SELECT DISTINCT ON (product_id)
    product_id,
    close
  FROM bars
  ORDER BY product_id, bucket_start
)

SELECT
  to_timestamp(b.bucket_start) AS "time",
  b.product_id AS metric,
  -- nullif guards a zero base. Without it one bad series divides by zero and
  -- fails the whole panel rather than just itself.
  100.0 * b.close / nullif(f.close, 0) AS value
FROM bars b
-- INNER, not LEFT: a pair with no bar in the window has no base to index
-- against, and emitting NULLs would add a legend entry that reads as a broken
-- series rather than one this venue does not carry.
INNER JOIN base f ON f.product_id = b.product_id
ORDER BY 1, 2
