-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: fx-analytics.json
-- Regenerate: make dashboard-sql

SELECT DISTINCT legs.c
FROM (
  SELECT i.product_id, i.base AS c FROM instruments i
  UNION ALL
  SELECT i.product_id, i.quote FROM instruments i
) legs
WHERE EXISTS (
  SELECT 1
  FROM instrument_registry r
  WHERE r.source = ${venue_source:sqlstring}
    AND r.product_id = legs.product_id
)
ORDER BY 1
