-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: fx-analytics.json
-- Regenerate: make dashboard-sql

SELECT DISTINCT product_id FROM cex_prices WHERE source = '$venue_source' ORDER BY 1
