-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: fx-analytics.json
-- Regenerate: make dashboard-sql

SELECT i.product_id
FROM instruments i
INNER JOIN instrument_liveness l ON l.product_id = i.product_id
WHERE ${currency:sqlstring} IN (i.base, i.quote)
  AND (${include_quiet:sqlstring} = 'all' OR l.is_live)
  AND EXISTS (
    SELECT 1
    FROM instrument_registry r
    WHERE r.source = ${venue_source:sqlstring}
      AND r.product_id = i.product_id
  )
ORDER BY 1
