-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: fx-analytics.json
-- Regenerate: make dashboard-sql

SELECT min(bucket_start) * 1000 FROM cex_prices WHERE source = '$venue_source' AND product_id = '$venue_product' AND granularity_secs::text = '$granularity'
