-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: fx-analytics.json
-- Regenerate: make dashboard-sql

SELECT i.product_id FROM instruments AS i WHERE ${currency:sqlstring} IN (i.base, i.quote) AND EXISTS (SELECT 1 FROM instrument_registry AS r WHERE r.source = ${venue_source:sqlstring} AND r.product_id = i.product_id) ORDER BY 1
