-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: fx-analytics.json
-- Regenerate: make dashboard-sql

SELECT DISTINCT product_id FROM spot_ticks WHERE source = ANY (ARRAY[${tick_source:sqlstring}]::text[]) ORDER BY 1
