-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: fx-analytics.json
-- Regenerate: make dashboard-sql

SELECT DISTINCT granularity_secs FROM cex_prices WHERE source = '$venue_source' AND product_id = '$venue_product' ORDER BY 1
