-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: fx-analytics.json
-- Regenerate: make dashboard-sql

SELECT DISTINCT c.product_id FROM cex_prices AS c JOIN instruments AS i ON i.product_id = c.product_id WHERE c.source = ${venue_source:sqlstring} AND ${currency:sqlstring} IN (i.base, i.quote) ORDER BY 1
