#!/usr/bin/env python3
# cspell:word dedented
"""Mirror the Grafana dashboards' SQL into files, so it can be diffed and linted.

The dashboard JSON stays the source of truth. Nothing here writes to it; this
tool reads every panel query, annotation query and template-variable query out
of it and writes each to its own `.sql` file under a mirror tree. The mirror is
regenerated in the same commit as any dashboard edit, and `check` fails when the
two have drifted.

WHY A MIRROR RATHER THAN CANONICAL SQL FILES.

The alternative — SQL files as the source of truth, assembled into the JSON by a
build step — is a bigger change and buys little today: Grafana's own UI edits the
JSON, so a canonical-file design has to fight the tool the operator actually
uses. Extraction is the cheaper half of the same benefit, and escalating to
canonical files with a sync checker is deliberately deferred until extraction
proves insufficient.

WHAT THE MIRROR IS FOR.

1. **Diffs.** A one-character change inside a 1,500-character JSON string is
   invisible in review. The same change in a `.sql` file is a one-line diff.
2. **Lint.** `lint` substitutes the Grafana macros and template variables and
   runs sqlfluff over the result as Postgres — the only mechanical check this
   SQL has ever had.
3. **Guards.** Three failure modes are structural rather than stylistic, and all
   are silent in Grafana, so they are refused outright. See `check_macro_args`,
   `check_regex_in_literal`, and `check_bare_var_in_literal` — the last added
   after a review observed that closing 24 quoting sites by hand left nothing
   stopping the 25th.

THE ALERT RULES ARE COVERED TOO, and how they are read is deliberate.

The alert rules under `provisioning/alerting/*.yml` carry SQL in `rawSql` block
scalars, and they are mirrored and linted alongside the dashboards. This used to
be a documented exclusion on the grounds that parsing YAML needs a reader this
stdlib-only tool cannot have — but a stated exclusion is a hole every future
alert rule widens silently, which is the opposite of what a mirror gate is for.

PyYAML is NOT imported, and the reason is specific rather than dogmatic: the
`dashboard-sql-lint` hook runs under `language: python` with only sqlfluff in its
environment, so an `import yaml` on this shared code path would break that hook
while leaving `check` (a `language: system` hook, ambient interpreter) green. The
failure would appear in the gate that has nothing to do with the change.

So `rawSql` is lifted STRUCTURALLY rather than by a regex sweep of the file —
`block_scalar` implements YAML's block-scalar indentation rule, which is what
decides where such a value ends. A regex cannot do this correctly, and the macro
regex already taught this codebase that lesson once (see `MACRO_CALL`).

What keeps that reader honest is a test, not this paragraph: the suite runs under
the ambient interpreter, where PyYAML IS available, and asserts the stdlib reader
agrees with PyYAML byte-for-byte on the committed alerting files. The equivalence
is therefore mechanically checked on every run, and the day a rule uses a YAML
feature the subset reader does not cover, that test fails rather than the mirror
going quietly wrong. `parse_alerting` refuses a folded (`>`) scalar outright for
the same reason — folding rewrites newlines, which would corrupt SQL silently.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import subprocess
import sys
import tempfile

# The dashboards, and where their extracted SQL lands.
DASHBOARD_DIR = pathlib.Path("market-data/grafana/dashboards")
MIRROR_DIR = pathlib.Path("market-data/grafana/sql")

# The provisioned alert rules, whose queries mirror into `alerting/` under the
# same tree. Keyed on the rule `uid` rather than on the filename or a positional
# index: a uid is unique across the org by definition (that is what a uid IS),
# it is the handle Grafana itself uses, and it survives a rule being reordered
# or moved between group files — none of which is true of a position. The
# duplicate-path guard in `collect` enforces the uniqueness rather than assuming
# it, so a copy-pasted uid is refused with a message naming the collision.
ALERTING_DIR = pathlib.Path("market-data/grafana/provisioning/alerting")

# A generated-file banner, so nobody edits the mirror expecting it to take
# effect. It names the tool AND the source, because the useful question when
# staring at one of these is "where do I make the change".
BANNER = (
    "-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.\n"
    "-- Source: {source}\n"
    "-- Regenerate: make dashboard-sql\n"
)

# Grafana's own macro parser captures a macro argument with a regex that stops at
# the FIRST closing paren, so a nested call inside a macro argument is silently
# truncated and the query then fails to interpolate. Three dashboard queries
# already carry comments explaining they were written around this, which is how
# a platform constraint becomes tribal knowledge — hence the guard.
MACRO_CALL = re.compile(r"\$__([A-Za-z_]+)\s*\(")

# Template variable references: `$name`, `${name}`, `${name:format}`.
#
# The format part allows several colon-separated segments, because Grafana's
# built-ins use them — `${__from:date:iso}`. Matching only one segment left that
# form unmatched by BOTH alternatives (the bare branch cannot start at `{`), so
# it survived substitution verbatim and reached sqlfluff as a parse error
# attributed to the panel's SQL rather than to this shim.
VAR_REF = re.compile(
    r"\$(?:\{(?P<braced>[A-Za-z0-9_]+)(?::(?P<fmt>[a-z][a-z:]*))?\}"
    r"|(?P<bare>[A-Za-z0-9_]+))"
)

# Deterministic stand-ins for the macros, chosen so the substituted text is valid
# Postgres and preserves the surrounding expression's TYPE. The point is to let a
# parser see the query's shape, not to reproduce Grafana's output.
MACRO_SUBSTITUTIONS = {
    "timeFilter": "{arg} BETWEEN '2024-01-01T00:00:00Z' AND '2024-01-02T00:00:00Z'",
    "timeGroup": "date_trunc('minute', {arg})",
    "timeGroupAlias": "date_trunc('minute', {arg})",
    "unixEpochFilter": "{arg} BETWEEN 1700000000 AND 1700086400",
    "unixEpochGroup": "(({arg}) / 60 * 60)",
    "unixEpochGroupAlias": "(({arg}) / 60 * 60)",
    "unixEpochNanoFilter": (
        "{arg} BETWEEN 1700000000000000000 AND 1700086400000000000"
    ),
}

# Macros taking no argument, substituted verbatim.
#
# Applied LONGEST KEY FIRST, which is required rather than cosmetic:
# `$__interval` is a prefix of `$__interval_ms`, so replacing the short one
# first turns the long one into `'1 minute'_ms` silently. The substitution loop
# sorts by length, so this dict's own order does not matter and a future
# alphabetizing edit cannot reintroduce the bug.
BARE_MACRO_SUBSTITUTIONS = {
    "$__timeFrom()": "'2024-01-01T00:00:00Z'",
    "$__timeTo()": "'2024-01-02T00:00:00Z'",
    "$__interval_ms": "60000",
    "$__interval": "'1 minute'",
    "$__rate_interval": "'1 minute'",
}


class ExtractionError(Exception):
    """A dashboard query the tool refuses to accept."""


def slug(text: str | None, fallback: str) -> str:
    """A stable, filesystem-safe fragment of a panel or variable title."""
    s = re.sub(r"[^a-z0-9]+", "-", (text or "").lower()).strip("-")
    return s[:60] or fallback


def lexical_scan(sql: str) -> tuple[list[tuple[int, int]], list[tuple[int, int]]]:
    """Split `sql` into (string-literal spans, non-code spans).

    One scanner for both guards, because they need the same lexical facts and
    had drifted apart: the regex guard skipped comments while the macro guard
    read the raw text, so a macro named in a comment was refused as if it were
    code.

    **Every lexical state here is load-bearing, and each one was a live
    inversion bug.** The scanner recognizes four things, and getting any of them
    wrong shifts every span after it and INVERTS the inside/outside verdict for
    the rest of the query:

    - **`--` line comments.** An apostrophe in ordinary prose — "the estimator's
      output", "Grafana's macro parser" — otherwise opens a phantom literal that
      never closes. This one actually shipped: it made the regex guard detect 6
      of 14 real sites while reporting green, and was found only because two
      identical `~ '^${v:regex}$'` constructs were classified differently either
      side of such a comment.
    - **`/* */` block comments, counted for DEPTH.** Postgres nests them, per
      the SQL standard, so `/* a /* b */ Grafana's parser */` ends at the second
      `*/`, not the first. A non-nesting scan resumes inside the outer comment
      and the apostrophe in "Grafana's" opens a phantom literal.
    - **`"` quoted identifiers.** These dashboards use them heavily and by
      necessity — Grafana binds a time series on `AS "time"` and the candlestick
      panel on `"open"`/`"high"`/`"low"`/`"close"` — so this is not an exotic
      case. `"it's"` would open a phantom literal, and worse, `"col--name"`
      would start a line comment that swallows the rest of the line INCLUDING
      any real literal on it. That direction is the dangerous one: a missed
      literal means the regex guard reports green on a genuine site.
    - **`'` literals**, with a doubled quote as an escape: `'it''s'` is one
      literal, not two.

    Dollar-quoted strings and `E''` escape strings are still NOT handled; no
    dashboard query uses either. If one ever does, this function is what
    silently weakens, so it is named here rather than left to be rediscovered.
    An unterminated literal yields a span to end-of-input — over-detection,
    which is the safe direction. An unterminated block comment swallows the
    rest, which is the unsafe direction, but an unterminated block comment is
    itself a Postgres syntax error and the lint gate's parse check covers it.
    """
    literals: list[tuple[int, int]] = []
    non_code: list[tuple[int, int]] = []
    i, n = 0, len(sql)
    while i < n:
        if sql.startswith("--", i):
            start = i
            nl = sql.find("\n", i)
            i = n if nl == -1 else nl + 1
            non_code.append((start, i))
            continue
        if sql.startswith("/*", i):
            start = i
            depth, i = 1, i + 2
            while i < n and depth:
                if sql.startswith("/*", i):
                    depth += 1
                    i += 2
                elif sql.startswith("*/", i):
                    depth -= 1
                    i += 2
                else:
                    i += 1
            non_code.append((start, i))
            continue
        if sql[i] == '"':
            start = i
            i += 1
            while i < n:
                if sql[i] == '"':
                    if i + 1 < n and sql[i + 1] == '"':
                        i += 2
                        continue
                    break
                i += 1
            i = min(i + 1, n)
            non_code.append((start, i))
            continue
        if sql[i] != "'":
            i += 1
            continue
        start = i
        i += 1
        while i < n:
            if sql[i] == "'":
                if i + 1 < n and sql[i + 1] == "'":
                    i += 2
                    continue
                break
            i += 1
        end = min(i + 1, n)
        literals.append((start, end))
        non_code.append((start, end))
        i = end
    return literals, non_code


def string_literal_spans(sql: str) -> list[tuple[int, int]]:
    """The string-literal spans of `sql`. See `lexical_scan` for the details."""
    return lexical_scan(sql)[0]


def in_literal(pos: int, spans: list[tuple[int, int]]) -> bool:
    return any(a <= pos < b for a, b in spans)


def macro_argument(sql: str, match: re.Match[str]) -> tuple[str, int]:
    """The text inside a macro call, and the index just past its closing paren."""
    depth, i, n = 1, match.end(), len(sql)
    start = i
    while i < n and depth:
        if sql[i] == "(":
            depth += 1
        elif sql[i] == ")":
            depth -= 1
        i += 1
    if depth:
        raise ExtractionError(f"unclosed `$__{match.group(1)}(` macro call")
    return sql[start : i - 1], i


def check_macro_args(sql: str, where: str) -> None:
    """Refuse a macro argument containing a paren.

    Grafana truncates the argument at the first `)`, so
    `$__timeGroup(to_timestamp(t), '1m')` reaches the datasource mangled and the
    panel fails to interpolate — with no error naming the cause. Refusing it here
    is the whole reason this guard exists.
    """
    _, non_code = lexical_scan(sql)
    for m in MACRO_CALL.finditer(sql):
        # Skip a macro NAMED in a comment or a quoted identifier. Its sibling
        # guard has always done this and this one did not, which made the two
        # disagree about the same text: three dashboard queries carry comments
        # explaining they were written around this very limitation, and the
        # natural way to write one is to quote the broken form — which this
        # guard would then refuse, with a message naming nothing the author can
        # act on.
        if in_literal(m.start(), non_code):
            continue
        try:
            arg, _ = macro_argument(sql, m)
        except ExtractionError as e:
            raise ExtractionError(f"{where}: {e}") from None
        if "(" in arg or ")" in arg:
            raise ExtractionError(
                f"{where}: `$__{m.group(1)}(...)` has a nested paren in its "
                f"argument ({arg.strip()!r}). Grafana's macro parser stops at "
                f"the first closing paren, so this argument is truncated and "
                f"the query fails to interpolate. Move the call into a CTE or "
                f"the SELECT list and hand the macro a bare column."
            )


def check_regex_in_literal(sql: str, where: str) -> None:
    """Refuse a `:regex`-formatted variable inside a single-quoted SQL literal.

    The regex formatter does not escape quotes, so `'^${source:regex}$'` is a
    quoting bug waiting for a value containing an apostrophe. Severity is bounded
    today — the datasource authenticates as a read-only role and the value
    domains are compile-time symbols — but the shape is wrong, and it spread by
    being copied from one panel to the next, which is exactly what a guard stops.

    The fix is per-query-shape rather than a formatter swap: `:sqlstring` quotes
    and escapes each value, so a multi-select regex match becomes
    `IN (${var:sqlstring})`.
    """
    spans = string_literal_spans(sql)
    for m in VAR_REF.finditer(sql):
        if m.group("fmt") == "regex" and in_literal(m.start(), spans):
            name = m.group("braced")
            # The recommendation is `= ANY (ARRAY[...]::text[])`, NOT
            # `IN (...)`. Both use the quote-escaping `:sqlstring` formatter,
            # but `IN ()` is a SYNTAX ERROR when the variable has no selected
            # options, whereas `ARRAY[]::text[]` is valid and matches nothing.
            # An author who followed an `IN (...)` recommendation would get a
            # query that errors on the empty case, and the natural next move is
            # to revert to the unsafe form this guard exists to stop.
            raise ExtractionError(
                f"{where}: `{m.group(0)}` is a regex-formatted variable inside "
                f"a single-quoted literal, and the regex formatter does not "
                f"escape quotes. Use "
                f"`= ANY (ARRAY[${{{name}:sqlstring}}]::text[])` — the "
                f"sqlstring formatter quotes and escapes every value, and the "
                f"ARRAY form stays valid SQL when nothing is selected, unlike "
                f"`IN ()`. Do not match `~` against an interpolated pattern."
            )


def check_bare_var_in_literal(sql: str, where: str) -> None:
    """Refuse an unformatted variable reference inside a single-quoted literal.

    The sibling guard above refuses the `:regex` form specifically, because the
    regex formatter is the one that provably does not escape quotes. But a
    BARE reference — `'$venue_source'`, `'${granularity}'` — carries the same
    exposure for the same reason: Grafana substitutes the raw value, so a value
    containing an apostrophe terminates the literal.

    That gap was closed by hand once, across 24 sites. A one-time sweep is not
    a gate: the 25th site would land with the mirror current and the lint hook
    green, and the shape spreads by being copied from one panel to the next —
    which is exactly what the sibling guard exists to stop. This makes the
    invariant hold by construction instead.

    A reference carrying ANY formatter is left alone. `:sqlstring` is the fix
    this recommends, and the others (`:csv`, `:json`, …) are deliberate choices
    whose escaping is the author's to reason about; only the unformatted form
    is unambiguously the copied mistake.
    """
    spans = string_literal_spans(sql)
    for m in VAR_REF.finditer(sql):
        if m.group("fmt") or not in_literal(m.start(), spans):
            continue
        name = m.group("braced") or m.group("bare") or ""
        # Grafana's own `$__`-prefixed macros are substituted by the datasource
        # before the query is sent, so they are not user-supplied values and a
        # quoted one is not this defect.
        if name.startswith("__"):
            continue
        # `VAR_REF`'s bare alternative accepts a LEADING DIGIT, because it is
        # shared with `substitute` and only ever had to be greedy there. A
        # guard cannot be: a currency format mask (`to_char(x, '$999.00')`), a
        # positional marker (`'$1'`), or a regex literal are all ordinary SQL
        # that contain a dollar-digit run inside a literal, and refusing them
        # would leave no way past except editing this tool. A Grafana variable
        # name cannot start with a digit, so requiring a leading letter or
        # underscore separates the two exactly. Narrowed HERE rather than in
        # `VAR_REF`, which `substitute` shares and which wants the wide form.
        if not name[:1].isalpha() and not name.startswith("_"):
            continue
        raise ExtractionError(
            f"{where}: `{m.group(0)}` is an unformatted variable inside a "
            f"single-quoted literal, so a value containing an apostrophe "
            f"terminates the literal. Use `${{{name}:sqlstring}}` without the "
            f"surrounding quotes — that formatter quotes and escapes the value "
            f"itself — or `= ANY (ARRAY[${{{name}:sqlstring}}]::text[])` for a "
            f"multi-select, which also stays valid SQL when nothing is "
            f"selected, unlike `IN ()`."
        )


def substitute(sql: str) -> str:
    """Replace macros and variables with deterministic stand-ins, for linting.

    Variables are typed by CONTEXT, which is the only way to get a parseable
    result: a reference inside a string literal becomes a bare word, one outside
    becomes a number, and a `:sqlstring` reference becomes a quoted word because
    that formatter's own output is already quoted. Guessing wrong does not
    produce a wrong lint — it produces a parse error, loudly.
    """
    for macro in sorted(BARE_MACRO_SUBSTITUTIONS, key=len, reverse=True):
        sql = sql.replace(macro, BARE_MACRO_SUBSTITUTIONS[macro])

    while True:
        m = MACRO_CALL.search(sql)
        if not m:
            break
        arg, end = macro_argument(sql, m)
        # A multi-argument macro's first argument is the column; the rest are
        # intervals the stand-in does not need.
        first = arg.split(",")[0].strip()
        template = MACRO_SUBSTITUTIONS.get(m.group(1))
        # An unknown macro collapses to its argument rather than being refused: a
        # new Grafana macro must not break the lint gate, and correctness is
        # enforced by the guards above, not here.
        replacement = template.format(arg=first or "1") if template else (first or "1")
        sql = sql[: m.start()] + replacement + sql[end:]

    # Variables, right-to-left so the literal spans stay valid as we edit.
    spans = string_literal_spans(sql)
    for m in reversed(list(VAR_REF.finditer(sql))):
        if m.group("fmt") == "sqlstring":
            replacement = "'x'"
        elif in_literal(m.start(), spans):
            replacement = "x"
        else:
            replacement = "1"
        sql = sql[: m.start()] + replacement + sql[m.end() :]
    return sql


def queries(dashboard: pathlib.Path) -> list[tuple[str, str]]:
    """Every SQL fragment in one dashboard, as (mirror-relative path, sql) pairs.

    Panels are walked including a row's nested `panels`, so a collapsed row's
    queries are not silently skipped. Template variables are filtered to
    `type == 'query'`: a `custom` variable's `query` holds a comma-separated
    option list, not SQL, and linting one would fail on the commas.
    """
    doc = json.loads(dashboard.read_text())
    name = dashboard.stem
    out: list[tuple[str, str]] = []

    def panels(container: dict) -> object:
        for p in container.get("panels", []) or []:
            yield p
            yield from panels(p)

    for panel in panels(doc):
        pid = panel.get("id")
        targets = panel.get("targets", []) or []
        # A panel carrying SQL but no `id` would reach the f-string below as
        # `f"{None:02d}"` and raise a bare TypeError straight out of a
        # pre-commit hook, bypassing the ExtractionError handler entirely.
        # Grafana assigns an id to every panel it saves, so this means a
        # hand-edited dashboard — say that instead.
        if pid is None and any(
            isinstance(t.get("rawSql"), str) and t.get("rawSql").strip()
            for t in targets
        ):
            raise ExtractionError(
                f"{dashboard.name}: a panel titled {panel.get('title')!r} "
                f"carries SQL but has no `id`. The mirror filename is keyed on "
                f"the id, which is the only stable handle a panel has."
            )
        title = slug(panel.get("title"), f"panel-{pid}")
        for idx, target in enumerate(targets):
            sql = target.get("rawSql")
            if not isinstance(sql, str) or not sql.strip():
                continue
            # The target index appears only when a panel has more than one, so
            # the common case keeps a clean filename.
            suffix = f"-{idx + 1}" if len(targets) > 1 else ""
            out.append((f"{name}/panel-{pid:02d}-{title}{suffix}.sql", sql))

    for idx, ann in enumerate(doc.get("annotations", {}).get("list", []) or []):
        sql = (ann.get("target") or {}).get("rawSql")
        if isinstance(sql, str) and sql.strip():
            title = slug(ann.get("name"), f"annotation-{idx}")
            out.append((f"{name}/annotation-{title}.sql", sql))

    for var in doc.get("templating", {}).get("list", []) or []:
        if var.get("type") != "query":
            continue
        sql = var.get("query")
        if not isinstance(sql, str) or not sql.strip():
            continue
        # Grafana stores the same SQL twice: `query` is what the datasource runs,
        # `definition` is what the variable editor displays. Nothing keeps them
        # in step, so editing one by hand leaves the UI describing a query that
        # is not the one running — a reader-misleading drift with no error. They
        # are required to agree rather than both being mirrored.
        definition = var.get("definition")
        if isinstance(definition, str) and definition.strip() and definition != sql:
            raise ExtractionError(
                f"{dashboard.name}: variable {var.get('name')!r} has a "
                f"`definition` that differs from its `query`. Grafana runs "
                f"`query` and displays `definition`, so this makes the variable "
                f"editor describe SQL that is not what executes. Set both to "
                f"the same text."
            )
        out.append((f"{name}/var-{slug(var.get('name'), 'unnamed')}.sql", sql))

    return out


# A block-scalar header: `key: |`, `key: |-`, `key: |+`, or the folded `>` forms.
# The indent is captured because it, not the key, is what bounds the value.
BLOCK_SCALAR = re.compile(
    r"^(?P<indent> *)(?P<key>[A-Za-z_][A-Za-z0-9_]*):"
    r"[ \t]*(?P<style>[|>])(?P<chomp>[-+]?)[ \t]*$"
)

# A rule's `uid`, anchored to the rule's own key indent. Anchoring matters: a
# `datasource:` mapping nested deeper inside a rule can carry its own `uid`, and
# an unanchored search would key the mirror on the DATASOURCE's uid instead —
# silently, and identically for every rule sharing that datasource, which the
# duplicate-path guard would then report as a collision naming the wrong cause.
# The unquoted alternative stops at whitespace rather than running to
# end-of-line: a trailing YAML comment (`uid: maker-paused # legacy`) would
# otherwise be captured into the value and slugged into the filename, where
# PyYAML yields the bare scalar. The quoted alternatives cannot hit this, which
# is why the asymmetry is worth spelling out.
RULE_UID = re.compile(r"^ *uid:[ \t]*(?:'([^']*)'|\"([^\"]*)\"|(\S+))[ \t]*(?:#.*)?$")


def indent_of(line: str) -> int:
    """The line's indentation width, in spaces.

    A TAB in the indentation is refused rather than measured. YAML forbids one
    there, and `lstrip(" ")` would silently measure a tab-indented line as
    indent 0 — which terminates an enclosing block scalar mid-query and
    truncates it. Truncation is the wrong direction for a gate: it produces
    wrong SQL rather than an error.
    """
    stripped = line.lstrip(" ")
    if stripped.startswith("\t"):
        raise ExtractionError(
            f"tab in the indentation of {line.strip()[:60]!r}; YAML forbids a "
            f"tab there, and measuring one would silently truncate the value"
        )
    return len(line) - len(stripped)


def block_body_end(lines: list[str], i: int, base: int) -> int:
    """The index just past the block-scalar body that follows `lines[i]`.

    Split out from `block_scalar` because BOTH scans need to SKIP a body
    without stripping its indentation or checking it against the block's
    width: a `description: >-` block is prose, and a scan only needs to know
    where the opaque region ends.

    Not validation-free, and the exception is worth naming rather than
    discovering: `indent_of` still refuses a TAB. That is deliberately
    conservative — this cannot tell a tab in the indentation, which YAML
    forbids, from one opening a content line, which YAML allows, so it refuses
    both. Refusing is the safe direction, since the alternative is measuring
    the line as indent 0 and truncating the value silently; the cost is that a
    legal tab-led content line is rejected rather than mirrored.
    """
    j = i + 1
    while j < len(lines):
        line = lines[j]
        if line.strip() and indent_of(line) <= base:
            break
        j += 1
    return j


def block_scalar(lines: list[str], i: int) -> tuple[str, int]:
    """The value of the block scalar whose header is `lines[i]`, and the next index.

    Implements YAML's block-scalar rule for the subset the provisioning files
    use. The value is every following line indented MORE than the header's own
    indent, dedented by the first NON-BLANK line's indentation, with blank
    lines kept as blanks (a blank line inside a block scalar carries no
    indentation to measure, so it must not be allowed to terminate the value).

    **The first non-blank line, not the first line.** A leading blank line
    would otherwise measure as indent 0 and leave the entire value carrying its
    YAML indentation, where PyYAML strips it — a silent divergence in the
    direction that matters, since the mirror is compared byte-for-byte.

    A line indented LESS than that width is **refused**, not sliced. Slicing it
    walks past its whitespace and removes a real character from the query, so
    the mirror would show SQL that is not what Grafana runs — and if the lost
    character lands somewhere sqlfluff still parses, the lint gate stays green
    too. PyYAML raises on the same input; refusing keeps the two in step.

    Chomping is honored because it changes the trailing bytes and the mirror is
    compared byte-for-byte: `-` strips every trailing newline, `+` keeps them
    all, and the default clips to exactly one.
    """
    m = BLOCK_SCALAR.match(lines[i])
    if not m:  # pragma: no cover - callers match first
        raise ExtractionError(f"line {i + 1} is not a block scalar header")
    base = len(m.group("indent"))

    j = block_body_end(lines, i, base)
    body = lines[i + 1 : j]

    # Trailing blank lines belong to the NEXT construct, not to this value —
    # except under `+`, which is what "keep" means. Count them rather than
    # recovering the number by arithmetic over indices later.
    trailing = 0
    while body and not body[-1].strip():
        body.pop()
        trailing += 1

    chomp = m.group("chomp")
    if not body:
        return ("\n" * trailing if chomp == "+" else ""), j

    strip = indent_of(next(line for line in body if line.strip()))
    for line in body:
        if line.strip() and indent_of(line) < strip:
            raise ExtractionError(
                f"the block scalar at line {i + 1} has a line indented less "
                f"than the block ({line.strip()[:60]!r}). YAML makes that an "
                f"error; stripping the block's indentation from it would "
                f"silently drop a real character from the value."
            )
    text = "\n".join(line[strip:] if line.strip() else "" for line in body)

    if chomp == "-":
        return text, j
    if chomp == "+":
        return text + "\n" * (1 + trailing), j
    return text + "\n", j


def parse_alerting(path: pathlib.Path) -> list[tuple[str, str]]:
    """Every `rawSql` in one alerting file, as (mirror-relative path, sql) pairs.

    Same shape as `queries` above, and worded the same deliberately: both feed
    the one `add()` closure in `collect`.

    The file is split into rules first and the uid read per rule, because the
    provisioning files keep their keys alphabetical (a house yamllint rule), so
    `uid` sorts AFTER `data` and is not available when the query is encountered.
    Buffering the rule is what lets a single pass key each query correctly.
    """
    lines = path.read_text().splitlines()

    # Rule items sit at one indent under `rules:`. Find that list, then treat
    # every `- ` at its item indent as a rule boundary.
    #
    # This tolerates a re-indent only where the dash stays in the same column
    # as `rules:` — the style these files use. Under `indent-sequences: true`
    # the dash would land one level deeper, match neither branch, and yield
    # zero rules; the mirror check then reports drift rather than going quiet,
    # but the message would name neither cause. The house yamllint config
    # pins the current style, so this is a stated limit rather than a risk.
    starts: list[int] = []
    # Where the rule list enclosing each start ENDS. Without this the LAST rule
    # of a list runs to end-of-file and absorbs everything after it — a sibling
    # group key, or a later top-level section such as `contactPoints:` — so a
    # `rawSql` down there is extracted under that rule's uid, and with the
    # not-a-literal-block refusal above, an unrelated one raises against the
    # wrong rule. Found by mutation-testing the reset branch, which closes the
    # list for the OTHER rules but could not close it for the final one.
    ends: dict[int, int] = {}
    open_starts: list[int] = []
    rules_indent: int | None = None

    def close_list(at: int) -> None:
        for s in open_starts:
            ends[s] = at
        open_starts.clear()

    idx = 0
    while idx < len(lines):
        line = lines[idx]
        stripped = line.strip()
        # Blank lines and comments carry no structure. They must NOT be allowed
        # to close the rule list: these files comment heavily, and every rule in
        # the committed set is preceded by a comment block explaining its
        # thresholds — so treating a comment as a sibling key ended the list
        # before the first rule and extracted nothing at all, silently.
        if not stripped or stripped.startswith("#"):
            idx += 1
            continue
        # A block scalar's BODY is opaque content, not structure, so the scan
        # jumps over it. Walking it line by line lets a QUERY containing a line
        # reading `rules:`, or a `- ` at the list's own column, fabricate or
        # close a rule boundary — silently, and yielding a wrong
        # (uid, sql) pairing rather than an error. The committed files are safe
        # from that only because their SQL sits at indent 10 while the rule list
        # sits at 2, which is a numeric coincidence of the current layout and
        # not a property of the parser.
        header = BLOCK_SCALAR.match(line)
        if header:
            idx = block_body_end(lines, idx, len(header.group("indent")))
            continue
        indent = indent_of(line)
        if stripped == "rules:":
            close_list(idx)
            rules_indent = indent
            idx += 1
            continue
        if rules_indent is None:
            idx += 1
            continue
        if stripped.startswith("- ") and indent == rules_indent:
            starts.append(idx)
            open_starts.append(idx)
        elif indent <= rules_indent:
            close_list(idx)
            rules_indent = None
        idx += 1
    close_list(len(lines))

    out: list[tuple[str, str]] = []
    for n, start in enumerate(starts):
        end = ends[start]
        if n + 1 < len(starts) and starts[n + 1] < end:
            end = starts[n + 1]
        rule = lines[start:end]
        # The rule's key indent: `  - annotations:` puts keys two past the dash.
        key_indent = (len(rule[0]) - len(rule[0].lstrip(" "))) + 2

        uid = None
        for line in rule:
            if len(line) - len(line.lstrip(" ")) != key_indent:
                continue
            m = RULE_UID.match(line)
            if m:
                uid = m.group(1) or m.group(2) or m.group(3)
                break

        # The rule's handle for an error message: its uid where it has one,
        # its title otherwise. Resolved once so every raise below names the
        # rule the same way — a rule that is BOTH uid-less and malformed
        # otherwise reports neither handle.
        handle = uid or rule_title(rule, key_indent)

        found: list[str] = []
        i = 0
        while i < len(rule):
            m = BLOCK_SCALAR.match(rule[i])
            if not m or m.group("key") != "rawSql":
                # SKIP ANOTHER KEY'S BLOCK-SCALAR BODY, exactly as the
                # boundary scan above does. These rules carry prose blocks
                # (`description: >-`, `summary: |-`), and walking into one
                # line by line reads its CONTENT as structure: a prose line
                # shaped like `something: |` would be taken for a header, and
                # one merely starting `rawSql:` would trip the refusal below
                # and fail the mirror gate on an annotation. The two scans
                # have to state the same rule or the asymmetry becomes a bug
                # the moment either one grows a check.
                if m:
                    i = block_body_end(rule, i, len(m.group("indent")))
                    continue
                # A `rawSql` that is not a literal block scalar must be
                # REFUSED, never skipped. Skipping it writes no mirror file, so
                # `check` stays green and the query is never linted — which is
                # precisely the silent hole this module's docstring argues
                # against. Reachable forms: a quoted single-line scalar
                # (`rawSql: 'SELECT 1'`), an explicit indentation indicator
                # (`rawSql: |2-`), a trailing comment after the indicator, and
                # the sequence-item form (`- rawSql: |-`), which the anchored
                # header pattern does not match either.
                bare = rule[i].strip()
                if bare.startswith("rawSql:") or bare.startswith("- rawSql:"):
                    raise ExtractionError(
                        f"{path.name}: rule {handle!r} writes its `rawSql` in "
                        f"a form this reader does not lift "
                        f"({rule[i].strip()[:60]!r}). Only a plain literal "
                        f"block (`rawSql: |-`) is mirrored, so any other form "
                        f"would be silently left out of the mirror, and so "
                        f"never linted — write it "
                        f"as a literal block."
                    )
                i += 1
                continue
            if m.group("style") == ">":
                raise ExtractionError(
                    f"{path.name}: rule {handle!r} writes its "
                    f"`rawSql` as a folded (`>`) scalar. Folding replaces the "
                    f"newlines with spaces, so the SQL Grafana runs is not the "
                    f"SQL as written — use a literal (`|-`) block."
                )
            sql, i = block_scalar(rule, i)
            if sql.strip():
                found.append(sql)

        if found and not uid:
            raise ExtractionError(
                f"{path.name}: an alert rule titled {handle!r} carries SQL but "
                f"has no `uid`. The mirror filename is keyed on the uid, which "
                f"is the only stable handle a rule has."
            )

        for idx, sql in enumerate(found):
            # The index appears only when a rule has more than one query, so the
            # common case keeps a clean filename — the same idiom the panel
            # targets use above.
            suffix = f"-{idx + 1}" if len(found) > 1 else ""
            out.append((f"alerting/{slug(uid, 'rule')}{suffix}.sql", sql))

    return out


def rule_title(rule: list[str], key_indent: int) -> str:
    """A rule's `title`, for an error message naming a rule that has no uid."""
    for line in rule:
        if len(line) - len(line.lstrip(" ")) != key_indent:
            continue
        if line.strip().startswith("title:"):
            return line.split(":", 1)[1].strip().strip("'\"")
    return "<untitled>"


def render(source: str, sql: str) -> str:
    body = sql if sql.endswith("\n") else sql + "\n"
    return BANNER.format(source=source) + "\n" + body


def collect(
    dashboard_dir: pathlib.Path,
    alerting_dir: pathlib.Path | None = None,
) -> dict[str, str]:
    """Every mirror file the dashboards and alert rules imply.

    Returned as {relative path: content}. `alerting_dir` is optional and a
    missing directory is not an error — the mirror gate must stay usable against
    a dashboard directory alone, which is what the tests do.
    """
    found: dict[str, str] = {}

    def add(source: str, rel: str, sql: str) -> None:
        where = f"{source} -> {rel}"
        check_macro_args(sql, where)
        check_regex_in_literal(sql, where)
        check_bare_var_in_literal(sql, where)
        if rel in found:
            raise ExtractionError(
                f"{where}: two queries claim the mirror path {rel!r}; "
                f"rename a panel, or give the alert rule its own uid, so the "
                f"extraction stays one-to-one"
            )
        found[rel] = render(source, sql)

    for dashboard in sorted(dashboard_dir.glob("*.json")):
        for rel, sql in queries(dashboard):
            add(dashboard.name, rel, sql)

    if alerting_dir is not None and alerting_dir.is_dir():
        for rules in sorted(alerting_dir.glob("*.yml")):
            for rel, sql in parse_alerting(rules):
                add(rules.name, rel, sql)

    return found


def cmd_extract(args: argparse.Namespace) -> int:
    wanted = collect(args.dashboards, args.alerting)
    args.mirror.mkdir(parents=True, exist_ok=True)
    written = 0

    for rel, content in sorted(wanted.items()):
        path = args.mirror / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists() or path.read_text() != content:
            path.write_text(content)
            written += 1

    # Prune orphans, or a renamed panel leaves its old mirror behind to be linted
    # forever and to read as a query that still exists.
    removed = 0
    for path in sorted(args.mirror.rglob("*.sql")):
        if str(path.relative_to(args.mirror)) not in wanted:
            path.unlink()
            removed += 1

    # And the now-empty per-dashboard directories. A deleted or renamed
    # dashboard otherwise leaves one behind forever, and `check` cannot see it:
    # its drift comparison walks `rglob("*.sql")`, so an empty directory is
    # invisible to the very gate that would report it. Deepest-first, so a
    # nested directory is removed before its parent is tested.
    for path in sorted(args.mirror.rglob("*"), reverse=True):
        if path.is_dir() and not any(path.iterdir()):
            path.rmdir()

    print(f"dashboard-sql: {len(wanted)} queries, {written} written, {removed} pruned")
    return 0


def cmd_check(args: argparse.Namespace) -> int:
    wanted = collect(args.dashboards, args.alerting)
    on_disk = {
        str(p.relative_to(args.mirror)): p.read_text()
        for p in args.mirror.rglob("*.sql")
    }
    missing = sorted(set(wanted) - set(on_disk))
    orphaned = sorted(set(on_disk) - set(wanted))
    changed = sorted(r for r in set(wanted) & set(on_disk) if wanted[r] != on_disk[r])

    if not (missing or orphaned or changed):
        print(f"dashboard-sql: {len(wanted)} queries, mirror up to date")
        return 0

    for rel in missing:
        print(f"  missing:  {rel}", file=sys.stderr)
    for rel in changed:
        print(f"  changed:  {rel}", file=sys.stderr)
    for rel in orphaned:
        print(f"  orphaned: {rel}", file=sys.stderr)
    print(
        "\ndashboard-sql: the mirror is out of date — run `make dashboard-sql` "
        "and commit the result alongside the dashboard change.",
        file=sys.stderr,
    )
    return 1


def cmd_lint(args: argparse.Namespace) -> int:
    """Substitute macros and variables, then lint the result as Postgres."""
    wanted = collect(args.dashboards, args.alerting)
    with tempfile.TemporaryDirectory() as tmp:
        root = pathlib.Path(tmp)
        for rel, content in sorted(wanted.items()):
            # Lint the QUERY, not the banner: sqlfluff has nothing useful to say
            # about a generated comment header.
            body = content.split("\n\n", 1)[1]
            path = root / rel
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(substitute(body))
        proc = subprocess.run(
            [
                sys.executable,
                "-m",
                "sqlfluff",
                "lint",
                "--config",
                str(args.sqlfluff_config),
                str(root),
            ],
            capture_output=True,
            text=True,
            check=False,
        )
        # Rewrite the temp paths back to the mirror path they came from, or every
        # diagnostic points at a directory that no longer exists.
        out = proc.stdout.replace(str(root) + "/", "")
        if out.strip():
            print(out)
        if proc.stderr.strip():
            print(proc.stderr, file=sys.stderr)
        return proc.returncode


def cmd_summary(args: argparse.Namespace) -> int:
    wanted = collect(args.dashboards, args.alerting)
    print(f"dashboard-sql: {len(wanted)} queries")
    for rel, content in sorted(wanted.items(), key=lambda kv: -len(kv[1])):
        print(f"  {len(content):5d}  {rel}")
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument(
        "command",
        choices=("extract", "check", "lint", "summary"),
        help="extract writes the mirror; check fails if it is stale; lint "
        "substitutes macros and runs sqlfluff; summary ranks queries by size",
    )
    ap.add_argument("--dashboards", type=pathlib.Path, default=DASHBOARD_DIR)
    ap.add_argument("--alerting", type=pathlib.Path, default=ALERTING_DIR)
    ap.add_argument("--mirror", type=pathlib.Path, default=MIRROR_DIR)
    ap.add_argument(
        "--sqlfluff-config",
        type=pathlib.Path,
        default=pathlib.Path("cfg/sqlfluff-dashboards.cfg"),
    )
    args = ap.parse_args(argv)

    try:
        return {
            "extract": cmd_extract,
            "check": cmd_check,
            "lint": cmd_lint,
            "summary": cmd_summary,
        }[args.command](args)
    except ExtractionError as e:
        print(f"dashboard-sql: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
