//! Expand the hand-written sBPF assembly under `src/asm/` into
//! `$OUT_DIR/combined.s`, which `lib.rs` links via
//! `anchor_asm_v2_runtime::include_asm!()` under the `asm-entrypoint`
//! feature. Runs on every build; the output is only linked when that
//! feature is on, so the default (reference) build is unaffected.
//!
//! Also lifts the assembly's `.equ` symbol table into
//! `$OUT_DIR/asm_equ.rs`, so `src/asm_offsets.rs` can assert every offset
//! the assembly hardcodes against the Rust layout **at compile time**. See
//! that module for why the check has to read the `.s` rather than re-state
//! its numbers.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;

/// The assembly the offset table is lifted out of.
const ENTRYPOINT_S: &str = "src/asm/entrypoint.s";

fn main() {
    anchor_asm_v2::build("src/asm");
    emit_equ_table();
}

/// Parse `ENTRYPOINT_S`'s `.equ` directives and write them to
/// `$OUT_DIR/asm_equ.rs` as `pub const` items.
fn emit_equ_table() {
    println!("cargo:rerun-if-changed={ENTRYPOINT_S}");
    let src = std::fs::read_to_string(ENTRYPOINT_S)
        .unwrap_or_else(|e| panic!("read {ENTRYPOINT_S}: {e}"));
    let symbols = parse_equ(&src);
    assert!(
        !symbols.is_empty(),
        "no `.equ` directives found in {ENTRYPOINT_S} — the parser and the \
         assembly have diverged, which would silently disable every offset \
         assertion in src/asm_offsets.rs",
    );

    let mut out =
        String::from("// @generated by build.rs from src/asm/entrypoint.s — do not edit.\n");
    for (name, value) in &symbols {
        writeln!(
            out,
            "/// `.equ {name}` as written in `src/asm/entrypoint.s`.\n\
             pub const {name}: u64 = {value};",
        )
        .expect("write to String");
    }
    let dest = Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR")).join("asm_equ.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("write {}: {e}", dest.display()));
}

/// Collect `\.equ NAME, EXPR` into a name → value table.
///
/// The grammar is only what the assembly actually uses: a decimal or `0x`
/// literal, or a sum of those and previously-defined symbols, as in
/// `MARKET_BASE + 2`. Definitions are resolved in file order, which is
/// enough because the assembly defines every symbol before referring to it.
/// Anything that does not parse is a hard error rather than a skip: a
/// silently dropped symbol would take its assertion with it.
fn parse_equ(src: &str) -> BTreeMap<String, u64> {
    let mut symbols = BTreeMap::new();
    for raw in src.lines() {
        // Strip the trailing `# …` comment before parsing.
        let line = raw.split('#').next().unwrap_or("").trim();
        let Some(rest) = line.strip_prefix(".equ ") else {
            continue;
        };
        let (name, expr) = rest
            .split_once(',')
            .unwrap_or_else(|| panic!("malformed .equ (no comma): {raw}"));
        let name = name.trim();
        let value = eval(expr, &symbols)
            .unwrap_or_else(|| panic!("cannot evaluate `.equ {name}` from: {raw}"));
        assert!(
            symbols.insert(name.to_owned(), value).is_none(),
            "duplicate `.equ {name}` in {ENTRYPOINT_S}",
        );
    }
    symbols
}

/// Evaluate one `.equ` right-hand side against the symbols defined so far.
fn eval(expr: &str, symbols: &BTreeMap<String, u64>) -> Option<u64> {
    let mut total: u64 = 0;
    for term in expr.split('+') {
        let term = term.trim();
        let value = if let Some(hex) = term.strip_prefix("0x") {
            u64::from_str_radix(hex, 16).ok()?
        } else if !term.is_empty() && term.bytes().all(|b| b.is_ascii_digit()) {
            term.parse().ok()?
        } else {
            *symbols.get(term)?
        };
        total = total.checked_add(value)?;
    }
    Some(total)
}
