-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: market-data.json
-- Regenerate: make dashboard-sql

SELECT
  source || ' ' || product_id AS feed,
  extract(epoch FROM now()) - max(bucket_start) AS age_secs
FROM cex_prices
WHERE source = ANY (ARRAY[${source:sqlstring}]::text[])
  AND product_id = ANY (ARRAY[${product_id:sqlstring}]::text[])
  AND granularity_secs = ${granularity:sqlstring}::bigint
GROUP BY 1
ORDER BY 1
