-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: market-data.json
-- Regenerate: make dashboard-sql

-- The candle tier's store inventory and its freshness in one definition,
-- absorbing what the old Last candle age tile and the FX dashboard's What is
-- in the store table each answered on their own.
--
-- DRIVEN FROM ALL TIME, windowed only in a column. A series that stopped
-- entirely has no rows inside any window, so a windowed GROUP BY drops it and
-- the reader cannot tell "stopped" from "never configured" -- that reading is
-- what the FX table contributed and it has to survive the merge. Here every
-- (source, product, bucket width) the store has ever held is a row, and
-- buckets_in_window falling to 0 is what says it stopped.
--
-- STALENESS IS CADENCE-RELATIVE, which is why age_secs is not the colored
-- column. A daily series is 86400 seconds old the moment before its next
-- bucket lands, so any absolute bound correct for 60s bars paints a healthy
-- daily reference permanently red -- the defect that made the FX table's
-- 300/3600 thresholds wrong rather than merely noisy, measured on a source
-- whose bars are 86400s wide. age_cadences divides by the series' own bucket
-- width, so one number reads correctly for both: about 1 is current, 2 is the
-- bucket in progress, and the colored bounds sit at 4 and 8 so a weekend of a
-- daily reference does not read like an outage.
WITH lifetime AS (
  SELECT
    c.source,
    c.product_id,
    c.granularity_secs,
    count(*) AS bars_all_time,
    max(c.bucket_start) AS last_bucket
  FROM cex_prices AS c
  GROUP BY 1, 2, 3
),

windowed AS (
  SELECT
    c.source,
    c.product_id,
    c.granularity_secs,
    count(*) AS buckets
  FROM cex_prices AS c
  WHERE c.bucket_start
    >= extract(epoch FROM now()) - (${coverage_mins:sqlstring}::bigint * 60)
  GROUP BY 1, 2, 3
)

SELECT
  l.source,
  l.product_id,
  l.granularity_secs,
  l.bars_all_time,
  coalesce(w.buckets, 0) AS buckets_in_window,
  to_timestamp(l.last_bucket) AS latest_bucket,
  (extract(epoch FROM now()) - l.last_bucket)::bigint AS age_secs,
  round(
    (extract(epoch FROM now()) - l.last_bucket) / l.granularity_secs, 1
  ) AS age_cadences
FROM lifetime AS l
LEFT JOIN windowed AS w
  ON
    l.source = w.source
    AND l.product_id = w.product_id
    AND l.granularity_secs = w.granularity_secs
ORDER BY 1, 2, 3
