-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: market-data.json
-- Regenerate: make dashboard-sql

-- The CTE is load-bearing, not style. Grafana captures macro
-- arguments with a regex that stops at the first closing paren, so
-- wrapping the epoch column in a to_timestamp call inside the
-- time-group macro leaves it one truncated argument and the query
-- fails to interpolate. Converting the column in a CTE first hands
-- the macro a bare column name, which is all it can parse. For the
-- same reason, do not name a macro in a comment here: the scanner
-- does not skip comments and will try to interpolate the example.
WITH bucketed AS (
  SELECT
    to_timestamp(bucket_start) AS bucket_ts,
    source
  FROM cex_prices
  WHERE $__unixEpochFilter(bucket_start)
    AND source = ANY (ARRAY[${source:sqlstring}]::text[])
    AND product_id = ANY (ARRAY[${product_id:sqlstring}]::text[])
    AND granularity_secs = ${granularity:sqlstring}::bigint
)
SELECT
  $__timeGroupAlias(bucket_ts, '1m', 0),
  source AS metric,
  count(*) AS value
FROM bucketed
GROUP BY 1, 2
ORDER BY 1
