-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: market-data.json
-- Regenerate: make dashboard-sql

-- Age thresholds are tighter than the candle panel's on purpose: a tick
-- feed polling every 15s that has printed nothing for a minute is behind
-- in a way a 60s candle series would not be.
SELECT
  source,
  product_id,
  count(*) AS prints,
  count(confidence) AS with_confidence,
  to_timestamp(max(observed_at)) AS latest_print,
  (extract(epoch FROM now()) - max(observed_at))::bigint AS age_secs
FROM spot_ticks
WHERE observed_at >= extract(epoch FROM now()) - ($coverage_mins * 60)
GROUP BY 1, 2
ORDER BY 1, 2
