-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: market-data.json
-- Regenerate: make dashboard-sql

-- Is every cursor-based collector process alive and committing right now, in
-- wall clock. This is the only true wall-clock liveness signal in the schema:
-- every other freshness reading measures when DATA last arrived, which a
-- closed venue suppresses even while the collector is perfectly healthy.
-- Measured instance of exactly that: after the Friday FX close oanda's cursor
-- was 33 seconds old while its newest candle was two hours old. Reading the
-- two as one number would have reported a collector outage that was not
-- happening.
--
-- SCOPED TO THE CURSOR-CAPABLE SOURCES, which is a deliberate narrowing of
-- the registry rather than a plain registry read. Only paged collectors commit
-- a cursor; kraken, erapi and frankfurter are HTTP live sources that must not
-- adopt Backfill at all, and pyth is parked, so a cursor for any of them
-- cannot exist. Joining the whole registry renders 73 rows of which 59 are
-- permanently empty -- strictly worse than the tile wall this replaces, and
-- the same "rows the reader learns to ignore" defect that cut the per-pair
-- long tail. Registry-driven WITHIN that scope still buys the property that
-- matters: a cursor row that disappears leaves its (source, product) behind as
-- a row, so an absence renders rather than vanishing.
--
-- AGE IS COUNTED IN EXPECTED COMMITS, not seconds, and that is what lets one
-- bound serve every source. The 300-second store-silence bound this panel
-- carries was written for the 60-second pollers, where it is five commits; a
-- daily collector is 86400 seconds old whenever it is perfectly healthy, so the
-- same absolute bound painted four alphavantage rows permanently red. Orange
-- at 3 and red at 5 carries the 300s bound over to a 60s source -- within the
-- rounding, which is one decimal, so red actually trips at 297.5s rather than
-- at 300s exactly -- while reading correctly for a daily one.
WITH expected AS (
  SELECT
    r.source,
    r.product_id,
    d.expected_secs
  FROM instrument_registry AS r
  INNER JOIN (VALUES
    ('oanda', 60),
    ('twelvedata', 60),
    ('coinbase', 60),
    ('alphavantage', 86400)
  ) AS d (source, expected_secs) ON r.source = d.source
)

SELECT
  e.source,
  e.product_id,
  (extract(epoch FROM now() - fc.updated_at))::bigint AS age_secs,
  round(
    extract(epoch FROM now() - fc.updated_at) / e.expected_secs, 1
  ) AS age_commits
FROM expected AS e
LEFT JOIN feed_cursors AS fc
  ON
    split_part(fc.feed, ':', 2) = e.source
    AND split_part(fc.feed, ':', 3) = e.product_id
ORDER BY
  age_commits DESC NULLS FIRST,
  e.source ASC,
  e.product_id ASC
