-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: market-data.json
-- Regenerate: make dashboard-sql

-- Can we quote right now. THE CRITERION IS ONE LIVE TRUSTED TAPE, halt at
-- zero -- ruled by the operator on 2026-09-10, replacing a "survives one or
-- two venues dark" reading that could not be implemented because it
-- contradicted itself. So the tape column is the only one that decides
-- anything; everything beside it is context.
--
-- The trusted tape is oanda, named here as a literal because primacy is a
-- DESIGNATION rather than a measurement -- it is the anchor treated as truth,
-- and no column in the store records that. Twelve Data carries the same pairs
-- intraday and is deliberately not believable alone, which is precisely why
-- the two must not be pooled into one count: one-live-of-two says nothing
-- until you know which one.
--
-- TAPE AGE IS THE HALT BOUND MADE READABLE, and it is the reading this panel
-- previously left implicit. The freshness picker IS the halt's detection
-- latency, so showing the tape's actual age beside the verdict is what lets a
-- reader see how far past the bound the tape has gone rather than only that it
-- failed. It is also the one column that distinguishes "quiet for a minute"
-- from "quiet since Friday" without a second panel.
--
-- WHY THERE IS NO CADENCE CLASSIFIER HERE, since the obvious way to write
-- this panel has one and it is a trap. An earlier version split sources into
-- intraday and daily by counting readings in a six-hour window, which fails
-- in the worst possible direction: a genuinely intraday venue that has been
-- down for more than six hours has no readings in the window, so it stops
-- counting as intraday and lands in the daily population -- while
-- instrument_source_liveness still reports it live, because that bound is 48
-- to 72 hours. A long outage therefore made the panel look HEALTHIER. Verified
-- against the store: a source can be is_live with zero readings in six hours.
--
-- Freshness alone does the work instead, and under the ruled criterion that
-- is sufficient rather than a compromise: cadence only ever mattered as a
-- proxy for "could this price a quote right now", and a designated tape plus
-- a recency test answers that directly, fail-closed.
--
-- THE LONG TAIL IS CUT to the anchors plus any pair with a live tape, with the
-- remainder counted in a final row. Those rows all read tape_live = 0, which on
-- a non-anchor pair is thirty-odd rows the reader must learn to ignore -- the
-- same defect that removed the constant dark column: a value that never varies
-- costs width and teaches the eye to skip the table. Be precise about what the
-- cut removes, because the obvious phrasing overstates it: a withheld pair may
-- well have live sources (every crypto and peg leg does, since `trusted` can
-- only ever be oanda), so the footer says "no live trusted tape" and not "no
-- live source". Source coverage below delivers by-name visibility for every
-- thin-roster currency, which is where a reader goes for those.
--
-- WHY `is_live` IS NOT CONJOINED WITH `fresh` in the three filters below. It
-- would be dead: the view's bound is 48 to 72 hours and `fresh` is minutes, so
-- `fresh` strictly implies `is_live` (confirmed against the store -- zero rows
-- are fresh without being live). Carrying it anyway would only invite the
-- reader to think this panel treats `is_live` as a quoting signal, which is
-- exactly the reading the spec rules out. It IS load-bearing in
-- stale_was_live, where the pair `is_live AND NOT fresh` is the transition
-- bucket itself.
--
-- THE MVP ANCHORS ARE A LITERAL, which is deliberate. There is no legitimate
-- state in which an MVP anchor is absent, so this panel has to be unable to
-- lose one. A de-rostered product leaves the registry, so a purely
-- registry-driven read would drop it silently -- the same
-- invisible-rather-than-dark defect the coverage panel exists to catch.
WITH anchor AS (
  SELECT a.product_id
  FROM (VALUES
    ('EUR-USD'),
    ('AUD-USD'),
    ('CAD-USD')
  ) AS a (product_id)
),

scope AS (
  SELECT a.product_id FROM anchor AS a
  UNION
  SELECT l.product_id FROM instrument_source_liveness AS l
),

graded AS (
  SELECT
    s.product_id,
    l.source,
    l.is_live,
    l.last_data_at,
    extract(epoch FROM now()) - l.last_data_at
      <= ${quote_freshness_mins:sqlstring}::bigint * 60 AS fresh,
    -- COUPLED to the exact source spelling the collectors register. The feeds
    -- framework names some sources per product (a venue can register as
    -- `venue:PRODUCT`), so if oanda ever adopted that shape this equality
    -- would stop matching and every pair would read no-go. That fails CLOSED
    -- -- a permanent false halt, loud rather than silent, and diagnosable
    -- because the venue still appears in printing_now -- which is why it is
    -- left as a plain equality rather than a prefix match that could also
    -- match a different venue whose name merely starts the same way.
    l.source = 'oanda' AS trusted
  FROM scope AS s
  LEFT JOIN instrument_source_liveness AS l ON l.product_id = s.product_id
),

per_pair AS (
  SELECT
    g.product_id,
    EXISTS (SELECT 1 FROM anchor AS a WHERE a.product_id = g.product_id)
      AS is_anchor,
    count(*) FILTER (WHERE g.trusted AND g.fresh) AS tape_live,
    max(g.last_data_at) FILTER (WHERE g.trusted) AS tape_last_at,
    -- One honest edge, visible rather than hidden: a daily reference counts
    -- here for the freshness window after it publishes, so this column can
    -- briefly read 1 on an FX pair whose only intraday tape is dead. That is
    -- why it is context and never a criterion -- it can never reach tape_live,
    -- so it can never clear the halt, which is what the ruling requires of a
    -- daily reference. Read it against printing_now, which names the source.
    count(*) FILTER (
      WHERE NOT g.trusted AND g.fresh
    ) AS corroborating,
    -- Where an outage lands FIRST, which is not where it stays: past the class
    -- bound the source drops out of is_live entirely, so this counter rises
    -- and then falls back. It is a TRANSITION bucket, not a cumulative one.
    count(*) FILTER (WHERE g.is_live AND NOT g.fresh) AS stale_was_live,
    string_agg(g.source, ', ' ORDER BY g.source) FILTER (
      WHERE g.fresh
    ) AS printing_now
  FROM graded AS g
  GROUP BY g.product_id
),

shown AS (
  SELECT p.* FROM per_pair AS p WHERE p.is_anchor OR p.tape_live > 0
),

withheld AS (
  SELECT count(*) AS n
  FROM per_pair AS p
  WHERE NOT (p.is_anchor OR p.tape_live > 0)
)

SELECT
  0 AS sort_group,
  s.product_id,
  s.tape_live,
  (extract(epoch FROM now()) - s.tape_last_at)::bigint AS tape_age_secs,
  s.corroborating,
  s.stale_was_live,
  s.printing_now
FROM shown AS s
UNION ALL
SELECT
  1 AS sort_group,
  w.n || ' further pairs withheld: no live trusted tape'
    AS product_id,
  NULL AS tape_live,
  NULL AS tape_age_secs,
  NULL AS corroborating,
  NULL AS stale_was_live,
  NULL AS printing_now
FROM withheld AS w
WHERE w.n > 0
ORDER BY 1 ASC, 3 ASC, 2 ASC
