-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: market-data.json
-- Regenerate: make dashboard-sql

-- Per-source fusion weights. Deliberately NOT filtered to weight > 0:
-- a zero-weight row is a source that answered and was trimmed, which
-- is the single most useful thing this table records. Filtering it out
-- would leave a fused estimate with no record of what it refused.
--
-- The mechanism filter IS required, though, and for the opposite reason.
-- The table is keyed by mechanism so the resolver's consensus attribution
-- can land additively; those weights are exact linear-combination shares
-- rather than shares of posterior information. Omitting this predicate
-- would plot two vocabularies on one axis and double every series the
-- day they arrive.
SELECT
  to_timestamp(ts) AS "time",
  market || ' ' || leg || ' ' || source AS metric,
  weight AS value
FROM maker_leg_contributions
WHERE $__unixEpochFilter(ts)
  AND mechanism = 'fusion'
  AND market = ANY (ARRAY[${market:sqlstring}]::text[])
ORDER BY 1
