-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: market-data.json
-- Regenerate: make dashboard-sql

-- Did a collector keep polling while storing nothing. Each store-sink batch
-- records the records it offered and the rows it actually wrote, so attrition
-- that used to leave only a debug log line is durable and readable here.
--
-- READ A RUN, NOT A ROW. A polling collector legitimately offers an empty
-- batch whenever the venue has not published the next bucket yet, so a
-- non-zero empty_intake count is ordinary. The reportable state is a feed
-- whose stored count is zero for the whole window while its market is open,
-- which is what the ordering below puts at the top.
--
-- ALL_DUPLICATE IS NOT ATTRITION. Delivery is at-least-once, so a resumed
-- window re-offers records the writer already holds and every one dedups
-- away. Those batches wrote zero rows and are behaving exactly as designed,
-- which is why they are counted apart from empty_intake rather than with it.
--
-- The aggregate is repeated in the ORDER BY rather than reusing the output
-- name: Postgres exposes an output column name to ORDER BY only as a bare
-- name, not inside an expression, so the alias would resolve against the
-- table and fail.
--
-- A feed that is not running has no row here at all, the same absence Tick
-- coverage carries: this table records batches that happened, so a source
-- parked by decision contributes nothing rather than a zero.
SELECT
  feed,
  count(*) AS batches,
  count(*) FILTER (WHERE outcome = 'stored') AS stored,
  count(*) FILTER (WHERE outcome = 'all_duplicate') AS all_duplicate,
  count(*) FILTER (WHERE outcome = 'empty_intake') AS empty_intake,
  sum(written) AS rows_written,
  max(observed_at) FILTER (WHERE outcome = 'stored') AS last_stored
FROM feed_batch_ingestion
WHERE $__timeFilter(observed_at)
GROUP BY feed
ORDER BY (count(*) FILTER (WHERE outcome = 'stored') = 0) DESC, feed
