-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: market-data.json
-- Regenerate: make dashboard-sql

SELECT
  feed,
  extract(epoch FROM now() - updated_at) AS age_secs
FROM feed_cursors
ORDER BY feed
