-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: market-data.json
-- Regenerate: make dashboard-sql

-- Live venues per pair: the quoting criterion, shown directly rather than by
-- implication.
--
-- THE CRITERION IS ONE LIVE TRUSTED TAPE, halt at zero -- ruled by the
-- operator on 2026-09-10, replacing a "survives one or two venues dark"
-- reading that could not be implemented because it contradicted itself. So
-- trusted_live is the only column that decides anything, and it is the only
-- one colored. Everything beside it is context: margin is what stands behind
-- the tape, not a second requirement.
--
-- The trusted tape is oanda, named here as a literal because primacy is a
-- DESIGNATION rather than a measurement -- it is the anchor treated as truth,
-- and no column in the store records that. Twelve Data carries the same pairs
-- intraday and is deliberately not believable alone, which is precisely why
-- the two must not be pooled into one count: one-live-of-two says nothing
-- until you know which one.
--
-- WHY THERE IS NO CADENCE CLASSIFIER HERE, since the obvious way to write
-- this panel has one and it is a trap. An earlier version split sources into
-- intraday and daily by counting readings in a six-hour window, which fails
-- in the worst possible direction: a genuinely intraday venue that has been
-- down for more than six hours has no readings in the window, so it stops
-- counting as intraday and lands in the daily population -- while
-- instrument_source_liveness still reports it live, because that bound is 48
-- to 72 hours. A long outage therefore made the panel look HEALTHIER, moving
-- a failed venue into a bucket that is supposed to look old. Verified against
-- the store: a source can be is_live with zero readings in six hours.
--
-- Freshness alone does the work instead, and under the ruled criterion that
-- is sufficient rather than a compromise: cadence only ever mattered as a
-- proxy for "could this price a quote right now", and a designated tape plus
-- a recency test answers that directly. It is also fail-closed, which the
-- classifier was not -- when the tape stops printing, trusted_live goes to
-- zero and stays there.
--
-- One honest edge, visible rather than hidden: a daily source counts toward
-- margin for the freshness window after it publishes. That is why margin is
-- context and not a criterion. It can never reach trusted_live, so it cannot
-- clear the halt -- which is exactly what the ruling requires of a daily
-- reference.
--
-- THE MVP ANCHORS ARE A LITERAL, which is deliberate and not an oversight.
-- There is no legitimate state in which an MVP anchor is absent, so this
-- panel has to be unable to lose one. A de-rostered product leaves the
-- registry, so a purely registry-driven read would drop it silently -- the
-- same invisible-rather-than-dark defect one level up that the coverage panel
-- exists to catch. Naming the three keeps a dark anchor rendering as a row of
-- zeros. They order first and are not otherwise displayed: the row order
-- already says it, so a column restating it would be sort machinery on show.
WITH anchor AS (
  SELECT * FROM (VALUES
    ('EUR-USD'),
    ('AUD-USD'),
    ('CAD-USD')
  ) AS a (product_id)
),

scope AS (
  SELECT product_id FROM anchor
  UNION
  SELECT product_id FROM instrument_source_liveness
),

graded AS (
  SELECT
    s.product_id,
    l.source,
    l.is_live,
    -- Read the liveness verdict from the view and the recency test here. The
    -- two answer different questions: is_live is "should this source be
    -- producing at all", on a class-aware bound that tolerates an FX weekend,
    -- while fresh is "is it producing right now".
    extract(epoch FROM now()) - l.last_data_at
      <= ${quote_freshness_mins:sqlstring}::bigint * 60 AS fresh,
    l.source = 'oanda' AS trusted
  FROM scope AS s
  LEFT JOIN instrument_source_liveness AS l ON l.product_id = s.product_id
)

SELECT
  g.product_id,
  count(*) FILTER (WHERE g.is_live AND g.trusted AND g.fresh) AS trusted_live,
  count(*) FILTER (
    WHERE g.is_live AND NOT g.trusted AND g.fresh
  ) AS margin,
  -- Where a real outage lands, and it can only go up. A daily source lives
  -- here too between publications, so this is not by itself a fault reading
  -- -- read it against fresh_sources to see which kind it is.
  count(*) FILTER (WHERE g.is_live AND NOT g.fresh) AS live_but_stale,
  count(*) FILTER (WHERE NOT g.is_live) AS dark,
  string_agg(g.source, ', ' ORDER BY g.source) FILTER (
    WHERE g.is_live AND g.fresh
  ) AS fresh_sources
FROM graded AS g
GROUP BY g.product_id
ORDER BY
  EXISTS (SELECT 1 FROM anchor AS a WHERE a.product_id = g.product_id) DESC,
  trusted_live ASC,
  g.product_id ASC
