-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: market-data.json
-- Regenerate: make dashboard-sql

-- The estimator's output over its raw inputs. Each arm is a bare
-- column inside the epoch-filter macro: Grafana captures a macro
-- argument with a regex that stops at the first closing paren, so a
-- to_timestamp(...) call inside one truncates the argument and the
-- query fails to interpolate. The conversion happens in the SELECT
-- list, never in the macro.
--
-- Raw prints: the scatter the fused line is judged against.
SELECT
  to_timestamp(observed_at) AS "time",
  source || ' ' || product_id || ' tick' AS metric,
  price AS value
FROM spot_ticks
WHERE $__unixEpochFilter(observed_at)
  AND source = ANY (ARRAY[${source:sqlstring}]::text[])
  AND product_id = ANY (ARRAY[${product_id:sqlstring}]::text[])
UNION ALL
-- The fair price: the composed mid the maker quotes off, which is now
-- built from the fused leg estimates rather than the bare medians.
-- NULL exactly when the composition paused, and left as a gap rather
-- than zero-filled -- a paused market and a market worth nothing are
-- different facts.
SELECT
  to_timestamp(ts) AS "time",
  market || ' fair (fused)' AS metric,
  fair AS value
FROM maker_telemetry
WHERE $__unixEpochFilter(ts)
  AND market = ANY (ARRAY[${market:sqlstring}]::text[])
  AND fair IS NOT NULL
UNION ALL
-- The FX leg's two numbers, which is where the estimator is actually
-- visible: `fused_value` is what the composition priced off and
-- `value` is the fast median that guards dislocations.
SELECT
  to_timestamp(ts) AS "time",
  market || ' fx estimate (fused)' AS metric,
  fused_value AS value
FROM maker_legs
WHERE $__unixEpochFilter(ts)
  AND market = ANY (ARRAY[${market:sqlstring}]::text[])
  AND leg = 'fx'
  AND fused_value IS NOT NULL
UNION ALL
SELECT
  to_timestamp(ts) AS "time",
  market || ' fx consensus (fast)' AS metric,
  value
FROM maker_legs
WHERE $__unixEpochFilter(ts)
  AND market = ANY (ARRAY[${market:sqlstring}]::text[])
  AND leg = 'fx'
ORDER BY 1
