-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: market-data.json
-- Regenerate: make dashboard-sql

-- Every source the collectors REGISTERED, whether or not it is producing.
-- The two coverage panels above group over a measurement table, so a source
-- that wrote nothing in the window has no rows to group and vanishes
-- entirely; absence there cannot be told apart from never having been
-- configured. Driving from the registry inverts that, and a dark collector
-- becomes a row reading 0 rather than a row that is not there.
--
-- PER (SOURCE, PRODUCT), NOT PER PRODUCT, and that is the whole point.
-- instrument_liveness answers the same question one level up and
-- deliberately drops the source, so a product some OTHER collector still
-- covers reads live and the dead one is masked. That masking is exactly the
-- defect this panel exists to catch, and instrument_source_liveness is the
-- view that keeps the source.
--
-- READ FROM THE VIEW, do not recompute. This panel first carried its own
-- copy of the two class-aware staleness bounds, because no per-source view
-- existed when it was written. One does now, and it defines those constants
-- once — so a copy here could only drift from them, and the whole reason the
-- thresholds live in one place is that a silent divergence between two
-- liveness verdicts is indistinguishable from a real outage. The view also
-- carries the granularity-vocabulary constraint that keeps the bars lookup
-- an index seek rather than a range scan, which this panel needs on a 5s
-- refresh and now inherits rather than restates.
SELECT
  source,
  count(*) AS products,
  count(last_data_at) AS ever_produced,
  count(*) FILTER (WHERE is_live) AS live,
  to_timestamp(max(last_data_at)) AS latest,
  (extract(epoch FROM now()) - max(last_data_at))::bigint AS age_secs
FROM instrument_source_liveness
GROUP BY source
ORDER BY live ASC, source ASC
