-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: market-data.json
-- Regenerate: make dashboard-sql

SELECT
  source,
  product_id,
  granularity_secs,
  count(*) AS buckets,
  to_timestamp(max(bucket_start)) AS latest_bucket,
  (extract(epoch FROM now()) - max(bucket_start))::bigint AS age_secs
FROM cex_prices
WHERE bucket_start >= extract(epoch FROM now()) - (${coverage_mins:sqlstring}::bigint * 60)
GROUP BY 1, 2, 3
ORDER BY 1, 2, 3
