-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: market-data.json
-- Regenerate: make dashboard-sql

SELECT
  to_timestamp(bucket_start) AS "time",
  "open",
  "high",
  "low",
  "close",
  "volume"
FROM cex_prices
WHERE $__unixEpochFilter(bucket_start)
  AND source = ${candle_source:sqlstring}
  AND product_id = ${product_id:sqlstring}
  AND granularity_secs = ${granularity:sqlstring}::bigint
ORDER BY bucket_start
