-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: market-data.json
-- Regenerate: make dashboard-sql

-- Candle closes and spot ticks in one series set. The tick half is
-- what makes this panel move BETWEEN candle closes: 60s is the finest
-- bucket any candle endpoint offers, so the candle half cannot show
-- intra-minute movement however often it is polled.
--
-- Tick series are suffixed so the legend distinguishes them from the
-- same venue's candle series, and they carry no granularity filter
-- because a tick has no bucket width.
SELECT
  to_timestamp(bucket_start) AS "time",
  source || ' ' || product_id AS metric,
  "close" AS value
FROM cex_prices
WHERE $__unixEpochFilter(bucket_start)
  AND source = ANY (ARRAY[${source:sqlstring}]::text[])
  AND product_id = ANY (ARRAY[${product_id:sqlstring}]::text[])
  AND granularity_secs = $granularity
UNION ALL
SELECT
  to_timestamp(observed_at) AS "time",
  source || ' ' || product_id || ' tick' AS metric,
  price AS value
FROM spot_ticks
WHERE $__unixEpochFilter(observed_at)
  AND source = ANY (ARRAY[${source:sqlstring}]::text[])
  AND product_id = ANY (ARRAY[${product_id:sqlstring}]::text[])
ORDER BY 1
