-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: market-data.json
-- Regenerate: make dashboard-sql

-- Every source the collectors REGISTERED, whether or not it is producing, and
-- the DESIGNATED role that says how to read its counts.
--
-- The two coverage tables below group over a measurement table, so a source
-- that wrote nothing has no rows to group and vanishes entirely; absence there
-- cannot be told apart from never having been configured. Driving from the
-- registry inverts that, and a dark collector becomes a row reading 0 rather
-- than a row that is not there.
--
-- THE ROSTER IS A DECLARED LITERAL, so this table has a FLOOR of eight rows:
-- SEVEN sources the platform expects to be RUNNING, declared below, plus one
-- per PARKED source, which the mirror joined below supplies rather than the
-- literal restating. A further row appears if the
-- registry ever holds a source nobody declared, which is the loud case below. A registry-only
-- read cannot promise that, because a source leaves the registry when its
-- collector stops registering -- exactly the invisible-rather-than-dark defect
-- one level up that this panel exists to catch. The full join is what makes it
-- fail closed in both directions: a declared source missing from the registry
-- still renders as a row of zeros, and a source in the registry that nobody
-- declared renders with role UNCLASSIFIED rather than blending in.
--
-- WHY ROLE IS A LITERAL AND NOT DERIVED. Whether a source is a designated tape
-- or a daily reference is a DESIGNATION, and no column in the store records
-- it. Every derivable form is the shape this run deleted: any cadence measured
-- from the readings themselves is suppressed by the very outage it must
-- report. A literal cannot be suppressed, at the cost of drifting when the
-- roster changes -- which is why an undeclared source is loud. The durable fix
-- is a collector-written cadence column in the registry, filed as a gap.
--
-- READ printing_now, NOT covered. covered is the view's class-aware bound, 48
-- to 72 hours, which answers "should this source be producing at all" and
-- tolerates an FX weekend; it was measured returning true at 24.6 hours old,
-- so it must never be read as a quoting signal. printing_now applies the tape
-- freshness bound instead and is the fail-closed reading. A daily reference
-- shows 0 there between publications BY DESIGN, and its role column is what
-- says so -- which is also why the two counts are no longer one column called
-- live, a name that invited reading five sources as five-fold redundancy when
-- the real intraday redundancy on an FX pair is two.
WITH declared AS (
  SELECT
    d.source,
    d.role
  FROM (VALUES
    ('oanda', 'tape (FX)'),
    ('twelvedata', 'intraday margin (FX)'),
    ('coinbase', 'tape (crypto/peg)'),
    ('kraken', 'tape (crypto/peg)'),
    ('alphavantage', 'daily reference'),
    ('erapi', 'daily reference'),
    ('frankfurter', 'daily reference')
  ) AS d (source, role)
),

-- THE PARKED SET, JOINED RATHER THAN COPIED. This used to be an eighth row in
-- the literal above reading 'parked by decision', which made this query hold
-- its own copy of a list that is decided in `feeds/src/parked.rs` -- the exact
-- copy-drift the declared roster exists to kill, one level in. The collectors
-- mirror the constant into `parked_sources` at startup, so a park supplies its
-- own row here and the two can no longer disagree.
--
-- `mirrored_at` is deliberately not shown. It dates the last COLLECTOR START,
-- not the park, so a reader would take it for a freshness signal; what it is
-- for is diagnosing a mirror that has fallen behind the constant, which is a
-- question about this table rather than about a source.
parked AS (
  SELECT
    p.venue AS source,
    p.since
  FROM parked_sources AS p
),

rolled AS (
  SELECT
    l.source,
    count(*) AS products,
    count(l.last_data_at) AS ever_produced,
    count(*) FILTER (WHERE l.is_live) AS covered,
    count(*) FILTER (
      WHERE
        extract(epoch FROM now()) - l.last_data_at
        <= ${quote_freshness_mins:sqlstring}::bigint * 60
    ) AS printing_now,
    max(l.last_data_at) AS latest
  FROM instrument_source_liveness AS l
  GROUP BY l.source
)

SELECT
  coalesce(r.source, d.source, k.source) AS source,
  coalesce(
    d.role,
    CASE WHEN k.source IS NOT NULL THEN 'parked by decision' END,
    'UNCLASSIFIED'
  ) AS role,
  k.since AS parked_since,
  coalesce(r.products, 0) AS products,
  coalesce(r.ever_produced, 0) AS ever_produced,
  coalesce(r.printing_now, 0) AS printing_now,
  coalesce(r.covered, 0) AS covered,
  to_timestamp(r.latest) AS latest,
  (extract(epoch FROM now()) - r.latest)::bigint AS age_secs
FROM rolled AS r
FULL JOIN declared AS d ON r.source = d.source
-- A THIRD FULL JOIN, for the same fail-closed reason as the second. A parked
-- source is in neither the registry nor the declared roster -- that is what
-- being parked means -- so an inner or left join would drop its row and this
-- panel would go back to being unable to say the word. Joining on the coalesce
-- of the two sides above is what lets a source that is BOTH declared and parked
-- still match one row rather than two.
FULL JOIN parked AS k ON coalesce(r.source, d.source) = k.source
-- ORDERED BY ROLE RANK, not alphabetically. Alphabetical put the three daily
-- references at the TOP -- and they read 0 under printing_now between
-- publications, so the first three rows of the table were permanently red while
-- the designated tape sat near the bottom. That is precisely the
-- teach-the-eye-to-skip-the-table defect cited twice above. An undeclared source
-- ranks first because it is the one thing here nobody has accounted for.
ORDER BY
  CASE coalesce(
    d.role,
    CASE WHEN k.source IS NOT NULL THEN 'parked by decision' END,
    'UNCLASSIFIED'
  )
    WHEN 'UNCLASSIFIED' THEN 0
    WHEN 'tape (FX)' THEN 1
    WHEN 'intraday margin (FX)' THEN 2
    WHEN 'tape (crypto/peg)' THEN 3
    WHEN 'daily reference' THEN 4
    -- Parked falls to this arm and so still sorts last, exactly where the
    -- literal row used to put it. Naming it in a WHEN would change nothing
    -- today and would quietly become wrong the moment a second state joins
    -- the ELSE.
    ELSE 5
  END ASC,
  coalesce(r.source, d.source, k.source) ASC
