-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: market-data.json
-- Regenerate: make dashboard-sql

SELECT min(c.bucket_start) * 1000 FROM cex_prices AS c WHERE c.source = ${candle_source:sqlstring} AND c.product_id = ANY (ARRAY[${product_id:sqlstring}]::text[]) AND c.granularity_secs::text = ${granularity:sqlstring}
