-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: market-data.json
-- Regenerate: make dashboard-sql

SELECT DISTINCT c.granularity_secs FROM cex_prices AS c WHERE c.product_id = ANY (ARRAY[${product_id:sqlstring}]::text[]) AND (c.source = ANY (ARRAY[${source:sqlstring}]::text[]) OR c.source = ${candle_source:sqlstring}) ORDER BY 1
