-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: maker-operations.json
-- Regenerate: make dashboard-sql

SELECT
  (extract(epoch FROM now()) - max(ts))::bigint AS "seconds since last sample"
FROM maker_telemetry
