-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: maker-operations.json
-- Regenerate: make dashboard-sql

SELECT
  bucket AS "time",
  sum(total_fee_lamports) AS "fee (lamports)"
FROM maker_quote_burn_hourly
WHERE $__timeFilter(bucket)
  AND market = ${market:sqlstring}
GROUP BY 1
ORDER BY 1
