-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: maker-operations.json
-- Regenerate: make dashboard-sql

SELECT
  to_timestamp(ts) AS "time",
  leg AS metric,
  confidence / value AS "confidence (fraction of value)"
FROM maker_legs
WHERE $__unixEpochFilter(ts)
  AND market = ${market:sqlstring}
  AND confidence IS NOT NULL
  AND value > 0
ORDER BY ts
