-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: maker-operations.json
-- Regenerate: make dashboard-sql

SELECT
  to_timestamp(ts) AS "time",
  fair AS "fair value",
  on_chain_reference AS "reference (on-chain)",
  reference AS "reference (candidate)",
  best_bid AS "best bid",
  best_ask AS "best ask"
FROM maker_telemetry
WHERE $__unixEpochFilter(ts)
  AND market = ${market:sqlstring}
ORDER BY ts
