-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: maker-operations.json
-- Regenerate: make dashboard-sql

WITH market AS (
  SELECT
    market_pubkey,
    power(10::numeric, base_decimals - quote_decimals) AS price_scale
  FROM maker_telemetry
  WHERE market = ${market:sqlstring}
  ORDER BY ts DESC
  LIMIT 1
)
SELECT
  to_timestamp(t.block_time) AS "time",
  (t.avg_price * m.price_scale)::double precision AS "fill"
FROM takes t
JOIN market m ON t.market = m.market_pubkey
WHERE $__unixEpochFilter(t.block_time)
ORDER BY t.block_time
