-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: maker-operations.json
-- Regenerate: make dashboard-sql

SELECT
  feed,
  state,
  to_timestamp(last_up_at) AS last_up,
  to_timestamp(last_down_at) AS last_down,
  connects,
  disconnects,
  to_timestamp(last_error_at) AS last_error_at,
  last_error
FROM push_health
ORDER BY state ASC, feed
