-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: maker-operations.json
-- Regenerate: make dashboard-sql

SELECT
  feed,
  status,
  coalesce(extract(epoch FROM now()) - last_ok_at, 9999999)::bigint AS ok_age_secs,
  to_timestamp(last_ok_at) AS last_ok,
  caught_up,
  last_records,
  ok_count,
  error_count,
  to_timestamp(last_error_at) AS last_error_at,
  last_error,
  to_timestamp(updated_at) AS last_seen
FROM feed_health
ORDER BY status ASC, feed
