-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: maker-operations.json
-- Regenerate: make dashboard-sql

SELECT
  to_timestamp(ts) AS "time",
  market,
  action,
  tick_error
FROM maker_telemetry
WHERE $__unixEpochFilter(ts)
  AND tick_error IS NOT NULL
ORDER BY ts DESC
LIMIT 100
