-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: maker-operations.json
-- Regenerate: make dashboard-sql

SELECT
  bucket AS "day (UTC)",
  market,
  kind,
  writes,
  base_fee_lamports,
  priority_fee_lamports,
  total_fee_lamports / 1e9 AS "total (SOL)"
FROM maker_quote_burn_daily
WHERE $__timeFilter(bucket)
ORDER BY bucket DESC, market, kind
