-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: maker-operations.json
-- Regenerate: make dashboard-sql

-- Every quoted level against the fair the maker priced off. The levels are
-- DERIVED rather than stored per tick: maker_ladder_epoch holds the armed
-- shape once per re-arm, on_chain_reference moves every tick, and a level's
-- price is the arithmetic the bot applies to the tightest level to get
-- best_bid / best_ask.
--
-- Three gates cover all four ways a side goes dark, and the split is the
-- point. size_bps > 0 catches every cause that goes THROUGH a re-arm, since
-- the epoch records sizes as armed: a halt zeroes both sides, a freeze-side
-- zeroes one. reference_valid and frozen catch the two that re-arm nothing,
-- so no epoch would ever show them. Both gates reject NULL, which is the
-- conservative direction -- a tick whose vault read failed draws no level
-- rather than a level that may not be resting.
WITH ticks AS (
  SELECT
    ts,
    fair,
    anchor,
    regime,
    on_chain_reference,
    reference_valid,
    frozen
  FROM maker_telemetry
  WHERE $__unixEpochFilter(ts)
    AND market = ${market:sqlstring}
),

-- Epoch validity windows are derived at EPOCH granularity -- from the distinct
-- armed_at -- and the levels are then joined onto them. Bracketing each
-- (side, level_idx) independently would be wrong whenever the ladder gets
-- SHORTER: the dropped index stops receiving rows, so its last window would
-- never be closed and the panel would keep drawing a deep level the bot has
-- not armed since. That direction over-states resting liquidity, which is the
-- one direction this panel must never take.
bounds AS (
  SELECT
    armed_at,
    lead(armed_at) OVER (ORDER BY armed_at) AS superseded_at
  FROM (
    SELECT DISTINCT armed_at
    FROM maker_ladder_epoch
    WHERE market = ${market:sqlstring}
  ) AS a
),

epochs AS (
  SELECT
    l.armed_at,
    l.side,
    l.level_idx,
    l.offset_ppm,
    l.size_bps,
    b.superseded_at
  FROM maker_ladder_epoch AS l
  INNER JOIN bounds AS b
    ON b.armed_at = l.armed_at
  WHERE l.market = ${market:sqlstring}
)

SELECT
  to_timestamp(t.ts) AS "time",
  e.side || ' L' || e.level_idx AS metric,
  (t.on_chain_reference * (
    1 + CASE e.side WHEN 'bid' THEN -1 ELSE 1 END
    * e.offset_ppm / 1000000.0
  ))::double precision AS value
FROM ticks AS t
INNER JOIN epochs AS e
  ON
    t.ts >= e.armed_at
    AND (e.superseded_at IS NULL OR t.ts < e.superseded_at)
WHERE
  t.reference_valid
  AND NOT t.frozen
  AND e.size_bps > 0
UNION ALL
SELECT
  to_timestamp(ts) AS "time",
  'fair value' AS metric,
  fair AS value
FROM ticks
UNION ALL
-- A market with no live leg publishes the STATIC PEG as a real price, at a
-- degraded regime anchored static -- so a 1.14 EURC print at bring-up is the
-- fallback constant rather than a composed mid. Drawn as its own series,
-- labelled with both the anchor and the regime, so a static print is visually
-- distinct from a composed one instead of reading as one. Overlays the
-- continuous fair line rather than replacing it, so the line keeps its shape.
--
-- 'Static' carries a capital S because maker_telemetry stores anchor as the Debug
-- rendering of the Anchor enum. The lowercase vocabulary (static, fx,
-- crypto_reference, none) belongs to the fair_price table, which writes
-- through explicit name mappers instead -- so the two tables spell the same
-- enum differently. If the maker's rendering ever changes, this predicate
-- stops matching and the overlay silently disappears.
SELECT
  to_timestamp(ts) AS "time",
  'fair (' || anchor || ' peg, ' || regime || ')' AS metric,
  fair AS value
FROM ticks
WHERE anchor = 'Static'
ORDER BY 1
