-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: maker-operations.json
-- Regenerate: make dashboard-sql

SELECT
  market,
  leg,
  consensus_state,
  contributor_count,
  dispersion_outlier,
  round(age_secs::numeric, 1) AS age_secs,
  fresh,
  to_timestamp(ts) AS observed
FROM (
  SELECT DISTINCT ON (market, leg) *
  FROM maker_legs
  WHERE ts > extract(epoch FROM now()) - 3600
  ORDER BY market, leg, ts DESC
) latest
ORDER BY market, leg
