-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: maker-operations.json
-- Regenerate: make dashboard-sql

SELECT
  to_timestamp(ts) AS "time",
  base_value_usd AS "base leg (USD)",
  quote_value_usd AS "quote leg (USD)",
  tvl_usd AS "TVL (USD)",
  launch_tvl_usd AS "launch TVL (USD)"
FROM maker_telemetry
WHERE $__unixEpochFilter(ts)
  AND market = ${market:sqlstring}
ORDER BY ts
