-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: maker-operations.json
-- Regenerate: make dashboard-sql

SELECT
  bucket AS "time",
  kind AS metric,
  writes
FROM maker_quote_burn_hourly
WHERE $__timeFilter(bucket)
  AND market = ${market:sqlstring}
ORDER BY 1
