-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: maker-operations.json
-- Regenerate: make dashboard-sql

-- Every quoted level against the fair the maker priced off. The levels are
-- DERIVED rather than stored per tick: maker_ladder_epoch holds the armed
-- shape once per re-arm, on_chain_reference moves every tick, and a level's
-- price is the arithmetic the bot applies to the tightest level to get
-- best_bid / best_ask.
--
-- Three gates cover all four ways a side goes dark, and the split is the
-- point. size_bps > 0 catches every cause that goes THROUGH a re-arm, since
-- the epoch records sizes as armed: a halt zeroes both sides, a freeze-side
-- zeroes one. reference_valid and frozen catch the two that re-arm nothing,
-- so no epoch would ever show them. Both gates reject NULL, which is the
-- conservative direction -- a tick whose vault read failed draws no level
-- rather than a level that may not be resting.
WITH ticks AS (
  SELECT
    ts,
    fair,
    on_chain_reference,
    reference_valid,
    frozen
  FROM maker_telemetry
  WHERE $__unixEpochFilter(ts)
    AND market = ${market:sqlstring}
),

epochs AS (
  SELECT
    armed_at,
    side,
    level_idx,
    offset_ppm,
    size_bps,
    lead(armed_at) OVER (
      PARTITION BY side, level_idx
      ORDER BY armed_at
    ) AS superseded_at
  FROM maker_ladder_epoch
  WHERE market = ${market:sqlstring}
)

SELECT
  to_timestamp(t.ts) AS "time",
  e.side || ' L' || e.level_idx AS metric,
  (t.on_chain_reference * (
    1 + CASE e.side WHEN 'bid' THEN -1 ELSE 1 END
    * e.offset_ppm / 1000000.0
  ))::double precision AS value
FROM ticks AS t
INNER JOIN epochs AS e
  ON
    t.ts >= e.armed_at
    AND (e.superseded_at IS NULL OR t.ts < e.superseded_at)
WHERE
  t.reference_valid
  AND NOT t.frozen
  AND e.size_bps > 0
UNION ALL
SELECT
  to_timestamp(ts) AS "time",
  'fair value' AS metric,
  fair AS value
FROM ticks
ORDER BY 1
