-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: maker-operations.json
-- Regenerate: make dashboard-sql

SELECT
  to_timestamp(ts) AS "time",
  leg AS metric,
  age_secs AS value
FROM maker_legs
WHERE $__unixEpochFilter(ts)
  AND market = ${market:sqlstring}
ORDER BY ts
