-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: maker-operations.json
-- Regenerate: make dashboard-sql

SELECT
  to_timestamp(ts) AS "time",
  skew_bps AS "reference skew (bps)"
FROM maker_telemetry
WHERE $__unixEpochFilter(ts)
  AND market = ${market:sqlstring}
ORDER BY ts
