-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: maker-operations.json
-- Regenerate: make dashboard-sql

-- Per-source fusion weights. Deliberately NOT filtered to weight > 0:
-- a zero-weight row is a source that answered and was trimmed, which
-- is the single most useful thing this table records. Filtering it out
-- would leave a fused estimate with no record of what it refused.
--
-- THE LEG SCOPE IS DELIBERATELY WIDER THAN THE PRICE ARMS, which is inherited
-- from the pre-merge panel rather than chosen here, and is stated because the
-- merge makes it newly visible. The estimator arms on the other target are
-- pinned to `leg = 'fx'`; these weights are not filtered by leg at all, so the
-- right-hand axis can carry a series for a leg that has no estimate line beside
-- it. The leg token in the metric name is what keeps that legible. Scoping it
-- to one leg would change what has shipped since the weights panel existed, so
-- it is left alone and flagged instead.
--
-- The mechanism filter IS required, though, and for the opposite reason.
-- The table is keyed by mechanism so the resolver's consensus attribution
-- can land additively; those weights are exact linear-combination shares
-- rather than shares of posterior information. Omitting this predicate
-- would plot two vocabularies on one axis and double every series the
-- day they arrive.
SELECT
  to_timestamp(ts) AS "time",
  market || ' ' || leg || ' ' || source || ' weight' AS metric,
  weight AS value
FROM maker_leg_contributions
WHERE $__unixEpochFilter(ts)
  AND mechanism = 'fusion'
  AND market = ANY (ARRAY[${market:sqlstring}]::text[])
ORDER BY 1
