-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: maker-operations.json
-- Regenerate: make dashboard-sql

SELECT i.product_id FROM instruments AS i JOIN currency_kinds AS m ON m.currency = upper(${market:sqlstring}) WHERE i.asset_class = ANY (ARRAY[${class:sqlstring}]::text[]) AND (m.currency IN (i.base, i.quote) OR m.pegged_to IN (i.base, i.quote)) ORDER BY 1
