-- GENERATED by .claude/tools/dashboard_sql.py — DO NOT EDIT.
-- Source: maker-operations.json
-- Regenerate: make dashboard-sql

SELECT DISTINCT market FROM maker_telemetry WHERE ts > extract(epoch FROM now()) - 86400 ORDER BY 1
