//! Execute the WASM `simulate_swap` binding and pin it to the native
//! matcher.
//!
//! The binding (`wasm::simulate_swap`) is the off-chain quote entry point
//! the TS client calls; it is `#[wasm_bindgen]`, so it only exists on
//! `wasm32` and never runs in a host `cargo test`. CI builds the wasm
//! target but does not execute it, so the decode + dispatch + marshalling
//! the binding adds over the native matcher are otherwise unproven. This
//! test runs the real compiled binding under `wasm-pack test --node`
//! (see .github/workflows/sdk.yml) over the checked-in
//! `sdk/conformance/simulate_swap_vectors.json` fixture and asserts each
//! `Quote` equals the native matcher's (which `sdk_conformance.rs` pins to
//! the on-chain engine in litesvm) — closing the wasm-binding == native ==
//! engine chain. The vectors are regenerated by `gen_simulate_swap`; see
//! its module docs for the fixture's scope and what it deliberately omits.
#![cfg(all(target_arch = "wasm32", feature = "wasm"))]

use dropset_interface::wasm::simulate_swap;
use serde_json::Value;
use wasm_bindgen_test::*;

/// Embedded at compile time: `include_str!` works in the wasm sandbox where
/// a runtime filesystem read would not.
const VECTORS: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../conformance/simulate_swap_vectors.json"
));

fn vectors() -> Value {
    serde_json::from_str(VECTORS).expect("parse simulate_swap_vectors.json")
}

fn market_data(v: &Value) -> Vec<u8> {
    v["market_data"]
        .as_array()
        .unwrap()
        .iter()
        .map(|b| b.as_u64().unwrap() as u8)
        .collect()
}

/// Every case: the binding's `Quote` must match the native matcher's,
/// proving the raw-bytes decode, `side: u8` dispatch, `Price::from_bits`,
/// and the `Quote` getters all marshal correctly across the boundary.
#[wasm_bindgen_test]
fn wasm_simulate_swap_matches_vectors() {
    let v = vectors();
    let data = market_data(&v);
    for c in v["cases"].as_array().unwrap() {
        let name = c["name"].as_str().unwrap();
        let side = c["side"].as_u64().unwrap() as u8;
        let amount_in = c["amount_in"].as_u64().unwrap();
        let limit_bits = c["limit_price_bits"].as_u64().unwrap() as u32;
        let slot = c["current_slot"].as_u64().unwrap() as u32;

        let q = simulate_swap(&data, side, amount_in, limit_bits, slot)
            .unwrap_or_else(|_| panic!("{name}: binding returned an error"));
        let e = &c["expected"];
        assert_eq!(
            q.in_amount(),
            e["in_amount"].as_u64().unwrap(),
            "{name}: in_amount"
        );
        assert_eq!(
            q.out_amount(),
            e["out_amount"].as_u64().unwrap(),
            "{name}: out_amount"
        );
        assert_eq!(
            q.fee_amount(),
            e["fee_amount"].as_u64().unwrap(),
            "{name}: fee_amount"
        );
        assert_eq!(
            u64::from(q.legs()),
            e["legs"].as_u64().unwrap(),
            "{name}: legs"
        );
    }
}

/// `side` is the one argument with no native analogue (the matcher takes a
/// `SwapSide` enum) — the binding maps `0`/`1` and must reject anything
/// else through the `JsError` path rather than silently picking a side.
#[wasm_bindgen_test]
fn wasm_simulate_swap_rejects_invalid_side() {
    let data = market_data(&vectors());
    assert!(
        simulate_swap(&data, 2, 1_000_000, u32::MAX, 1).is_err(),
        "side=2 must be rejected"
    );
}

/// The decode boundary: a buffer too short to hold the header surfaces
/// `MarketView::load`'s `LayoutError` as a `JsError`, not a panic across
/// the wasm boundary.
#[wasm_bindgen_test]
fn wasm_simulate_swap_rejects_undersized_buffer() {
    assert!(
        simulate_swap(&[0u8; 4], 0, 1_000_000, u32::MAX, 1).is_err(),
        "undersized market data must be rejected"
    );
}
